// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2004 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 01
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module fir_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              input_ch_id, 
              output_ch_id, 
              done, 
              rdy_to_ld, 
              fir_result ); 

parameter DATA_WIDTH  = 16;
parameter COEF_WIDTH  = 16;
parameter COEF_WIDTH_IN  = 16;
parameter ACCUM_WIDTH = 36;

parameter CH_WIDTH = 1;
 input clk, rst;
input [DATA_WIDTH -1 :0] data_in;
input clk_en;
output [CH_WIDTH -1 :0]input_ch_id;
output [CH_WIDTH -1 :0]output_ch_id;
output done;
wire done;
wire done_int;
wire data_ld;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
output [ACCUM_WIDTH-1:0] fir_result;

wire acc_rst_out;
wire coef_in_clk;
assign coef_in_clk = clk;
wire [15:0] tdl_dat_0_n;
wire [15:0] tdl_dat_0_ch_0_n;
wire [15:0] tdl_dat_1_n;
wire [15:0] tdl_dat_1_ch_0_n;
wire [15:0] tdl_dat_2_n;
wire [15:0] tdl_dat_2_ch_0_n;
wire [15:0] tdl_dat_3_n;
wire [15:0] tdl_dat_3_ch_0_n;
wire [15:0] tdl_dat_4_n;
wire [15:0] tdl_dat_4_ch_0_n;
wire [15:0] tdl_dat_5_n;
wire [15:0] tdl_dat_5_ch_0_n;
wire [15:0] tdl_dat_6_n;
wire [15:0] tdl_dat_6_ch_0_n;
wire [15:0] tdl_dat_7_n;
wire [15:0] tdl_dat_7_ch_0_n;
wire [15:0] tdl_dat_8_n;
wire [15:0] tdl_dat_8_ch_0_n;
wire [15:0] tdl_dat_9_n;
wire [15:0] tdl_dat_9_ch_0_n;
wire [15:0] tdl_dat_10_n;
wire [15:0] tdl_dat_10_ch_0_n;
wire [15:0] tdl_dat_11_n;
wire [15:0] tdl_dat_11_ch_0_n;
wire [15:0] tdl_dat_12_n;
wire [15:0] tdl_dat_12_ch_0_n;
wire [15:0] tdl_dat_13_n;
wire [15:0] tdl_dat_13_ch_0_n;
wire [15:0] tdl_dat_14_n;
wire [15:0] tdl_dat_14_ch_0_n;
wire [15:0] tdl_dat_15_n;
wire [15:0] tdl_dat_15_ch_0_n;
wire [15:0] tdl_dat_16_n;
wire [15:0] tdl_dat_16_ch_0_n;
wire [15:0] tdl_dat_17_n;
wire [15:0] tdl_dat_17_ch_0_n;
wire [15:0] tdl_dat_18_n;
wire [15:0] tdl_dat_18_ch_0_n;
wire [15:0] tdl_dat_19_n;
wire [15:0] tdl_dat_19_ch_0_n;
wire [15:0] tdl_dat_20_n;
wire [15:0] tdl_dat_20_ch_0_n;
wire [15:0] tdl_dat_21_n;
wire [15:0] tdl_dat_21_ch_0_n;
wire [15:0] tdl_dat_22_n;
wire [15:0] tdl_dat_22_ch_0_n;
wire [15:0] tdl_dat_23_n;
wire [15:0] tdl_dat_23_ch_0_n;
wire [15:0] tdl_dat_24_n;
wire [15:0] tdl_dat_24_ch_0_n;
wire [15:0] tdl_dat_25_n;
wire [15:0] tdl_dat_25_ch_0_n;
wire [15:0] tdl_dat_26_n;
wire [15:0] tdl_dat_26_ch_0_n;
wire [15:0] tdl_dat_27_n;
wire [15:0] tdl_dat_27_ch_0_n;
wire [15:0] tdl_dat_28_n;
wire [15:0] tdl_dat_28_ch_0_n;
wire [15:0] tdl_dat_29_n;
wire [15:0] tdl_dat_29_ch_0_n;
wire [15:0] tdl_dat_30_n;
wire [15:0] tdl_dat_30_ch_0_n;
wire [15:0] tdl_dat_31_n;
wire [15:0] tdl_dat_31_ch_0_n;
wire [15:0] tdl_dat_32_n;
wire [15:0] tdl_dat_32_ch_0_n;
wire [15:0] tdl_dat_33_n;
wire [15:0] tdl_dat_33_ch_0_n;
wire [15:0] tdl_dat_34_n;
wire [15:0] tdl_dat_34_ch_0_n;
wire [15:0] tdl_dat_35_n;
wire [15:0] tdl_dat_35_ch_0_n;
wire [15:0] tdl_dat_36_n;
wire [15:0] tdl_dat_36_ch_0_n;
wire [15:0] tdl_dat_37_n;
wire [15:0] tdl_dat_37_ch_0_n;
wire [15:0] tdl_dat_38_n;
wire [15:0] tdl_dat_38_ch_0_n;
wire [15:0] tdl_dat_39_n;
wire [15:0] tdl_dat_39_ch_0_n;
wire [15:0] tdl_dat_40_n;
wire [15:0] tdl_dat_40_ch_0_n;
wire [15:0] tdl_dat_41_n;
wire [15:0] tdl_dat_41_ch_0_n;
wire [15:0] tdl_dat_42_n;
wire [15:0] tdl_dat_42_ch_0_n;
wire [15:0] tdl_dat_43_n;
wire [15:0] tdl_dat_43_ch_0_n;
wire [15:0] tdl_dat_44_n;
wire [15:0] tdl_dat_44_ch_0_n;
wire [15:0] tdl_dat_45_n;
wire [15:0] tdl_dat_45_ch_0_n;
wire [15:0] tdl_dat_46_n;
wire [15:0] tdl_dat_46_ch_0_n;
wire [15:0] tdl_dat_47_n;
wire [15:0] tdl_dat_47_ch_0_n;
wire [15:0] tdl_dat_48_n;
wire [15:0] tdl_dat_48_ch_0_n;
wire [15:0] tdl_dat_49_n;
wire [15:0] tdl_dat_49_ch_0_n;
wire [15:0] tdl_dat_50_n;
wire [15:0] tdl_dat_50_ch_0_n;
wire [15:0] tdl_dat_51_n;
wire [15:0] tdl_dat_51_ch_0_n;
wire [15:0] tdl_dat_52_n;
wire [15:0] tdl_dat_52_ch_0_n;
wire [15:0] tdl_dat_53_n;
wire [15:0] tdl_dat_53_ch_0_n;
wire [15:0] tdl_dat_54_n;
wire [15:0] tdl_dat_54_ch_0_n;
wire [15:0] tdl_dat_55_n;
wire [15:0] tdl_dat_55_ch_0_n;
wire [15:0] tdl_dat_56_n;
wire [15:0] tdl_dat_56_ch_0_n;
wire [15:0] tdl_dat_57_n;
wire [15:0] tdl_dat_57_ch_0_n;
wire [15:0] tdl_dat_58_n;
wire [15:0] tdl_dat_58_ch_0_n;
wire [15:0] tdl_dat_59_n;
wire [15:0] tdl_dat_59_ch_0_n;
wire [15:0] tdl_dat_60_n;
wire [15:0] tdl_dat_60_ch_0_n;
wire [15:0] tdl_dat_61_n;
wire [15:0] tdl_dat_61_ch_0_n;
wire [15:0] tdl_dat_62_n;
wire [15:0] tdl_dat_62_ch_0_n;
wire [15:0] tdl_dat_63_n;
wire [15:0] tdl_dat_63_ch_0_n;
wire [15:0] tdl_dat_64_n;
wire [15:0] tdl_dat_64_ch_0_n;
wire [15:0] data_in_dd;
lc_store_cen Udin(.clk(clk), .rst(rst), .ce(rdy_int),.gclk_en(clk_en), .data_in(data_in),.q(data_in_dd) );
defparam Udin.WIDTH = 16;
tdl_da_lc tdl_ff_0_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(data_in_dd),.data_out(tdl_dat_0_ch_0_n));
defparam tdl_ff_0_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_0_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_0_ch_0_n),.data_out(tdl_dat_0_n));
defparam tdl_ff_0_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_1_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_0_n),.data_out(tdl_dat_1_ch_0_n));
defparam tdl_ff_1_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_1_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_1_ch_0_n),.data_out(tdl_dat_1_n));
defparam tdl_ff_1_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_2_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_1_n),.data_out(tdl_dat_2_ch_0_n));
defparam tdl_ff_2_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_2_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_2_ch_0_n),.data_out(tdl_dat_2_n));
defparam tdl_ff_2_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_3_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_2_n),.data_out(tdl_dat_3_ch_0_n));
defparam tdl_ff_3_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_3_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_3_ch_0_n),.data_out(tdl_dat_3_n));
defparam tdl_ff_3_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_4_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_3_n),.data_out(tdl_dat_4_ch_0_n));
defparam tdl_ff_4_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_4_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_4_ch_0_n),.data_out(tdl_dat_4_n));
defparam tdl_ff_4_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_5_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_4_n),.data_out(tdl_dat_5_ch_0_n));
defparam tdl_ff_5_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_5_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_5_ch_0_n),.data_out(tdl_dat_5_n));
defparam tdl_ff_5_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_6_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_5_n),.data_out(tdl_dat_6_ch_0_n));
defparam tdl_ff_6_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_6_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_6_ch_0_n),.data_out(tdl_dat_6_n));
defparam tdl_ff_6_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_7_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_6_n),.data_out(tdl_dat_7_ch_0_n));
defparam tdl_ff_7_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_7_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_7_ch_0_n),.data_out(tdl_dat_7_n));
defparam tdl_ff_7_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_8_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_7_n),.data_out(tdl_dat_8_ch_0_n));
defparam tdl_ff_8_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_8_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_8_ch_0_n),.data_out(tdl_dat_8_n));
defparam tdl_ff_8_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_9_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_8_n),.data_out(tdl_dat_9_ch_0_n));
defparam tdl_ff_9_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_9_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_9_ch_0_n),.data_out(tdl_dat_9_n));
defparam tdl_ff_9_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_10_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_9_n),.data_out(tdl_dat_10_ch_0_n));
defparam tdl_ff_10_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_10_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_10_ch_0_n),.data_out(tdl_dat_10_n));
defparam tdl_ff_10_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_11_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_10_n),.data_out(tdl_dat_11_ch_0_n));
defparam tdl_ff_11_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_11_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_11_ch_0_n),.data_out(tdl_dat_11_n));
defparam tdl_ff_11_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_12_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_11_n),.data_out(tdl_dat_12_ch_0_n));
defparam tdl_ff_12_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_12_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_12_ch_0_n),.data_out(tdl_dat_12_n));
defparam tdl_ff_12_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_13_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_12_n),.data_out(tdl_dat_13_ch_0_n));
defparam tdl_ff_13_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_13_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_13_ch_0_n),.data_out(tdl_dat_13_n));
defparam tdl_ff_13_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_14_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_13_n),.data_out(tdl_dat_14_ch_0_n));
defparam tdl_ff_14_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_14_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_14_ch_0_n),.data_out(tdl_dat_14_n));
defparam tdl_ff_14_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_15_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_14_n),.data_out(tdl_dat_15_ch_0_n));
defparam tdl_ff_15_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_15_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_15_ch_0_n),.data_out(tdl_dat_15_n));
defparam tdl_ff_15_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_16_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_15_n),.data_out(tdl_dat_16_ch_0_n));
defparam tdl_ff_16_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_16_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_16_ch_0_n),.data_out(tdl_dat_16_n));
defparam tdl_ff_16_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_17_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_16_n),.data_out(tdl_dat_17_ch_0_n));
defparam tdl_ff_17_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_17_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_17_ch_0_n),.data_out(tdl_dat_17_n));
defparam tdl_ff_17_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_18_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_17_n),.data_out(tdl_dat_18_ch_0_n));
defparam tdl_ff_18_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_18_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_18_ch_0_n),.data_out(tdl_dat_18_n));
defparam tdl_ff_18_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_19_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_18_n),.data_out(tdl_dat_19_ch_0_n));
defparam tdl_ff_19_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_19_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_19_ch_0_n),.data_out(tdl_dat_19_n));
defparam tdl_ff_19_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_20_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_19_n),.data_out(tdl_dat_20_ch_0_n));
defparam tdl_ff_20_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_20_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_20_ch_0_n),.data_out(tdl_dat_20_n));
defparam tdl_ff_20_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_21_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_20_n),.data_out(tdl_dat_21_ch_0_n));
defparam tdl_ff_21_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_21_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_21_ch_0_n),.data_out(tdl_dat_21_n));
defparam tdl_ff_21_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_22_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_21_n),.data_out(tdl_dat_22_ch_0_n));
defparam tdl_ff_22_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_22_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_22_ch_0_n),.data_out(tdl_dat_22_n));
defparam tdl_ff_22_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_23_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_22_n),.data_out(tdl_dat_23_ch_0_n));
defparam tdl_ff_23_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_23_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_23_ch_0_n),.data_out(tdl_dat_23_n));
defparam tdl_ff_23_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_24_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_23_n),.data_out(tdl_dat_24_ch_0_n));
defparam tdl_ff_24_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_24_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_24_ch_0_n),.data_out(tdl_dat_24_n));
defparam tdl_ff_24_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_25_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_24_n),.data_out(tdl_dat_25_ch_0_n));
defparam tdl_ff_25_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_25_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_25_ch_0_n),.data_out(tdl_dat_25_n));
defparam tdl_ff_25_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_26_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_25_n),.data_out(tdl_dat_26_ch_0_n));
defparam tdl_ff_26_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_26_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_26_ch_0_n),.data_out(tdl_dat_26_n));
defparam tdl_ff_26_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_27_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_26_n),.data_out(tdl_dat_27_ch_0_n));
defparam tdl_ff_27_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_27_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_27_ch_0_n),.data_out(tdl_dat_27_n));
defparam tdl_ff_27_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_28_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_27_n),.data_out(tdl_dat_28_ch_0_n));
defparam tdl_ff_28_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_28_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_28_ch_0_n),.data_out(tdl_dat_28_n));
defparam tdl_ff_28_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_29_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_28_n),.data_out(tdl_dat_29_ch_0_n));
defparam tdl_ff_29_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_29_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_29_ch_0_n),.data_out(tdl_dat_29_n));
defparam tdl_ff_29_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_30_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_29_n),.data_out(tdl_dat_30_ch_0_n));
defparam tdl_ff_30_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_30_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_30_ch_0_n),.data_out(tdl_dat_30_n));
defparam tdl_ff_30_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_31_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_30_n),.data_out(tdl_dat_31_ch_0_n));
defparam tdl_ff_31_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_31_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_31_ch_0_n),.data_out(tdl_dat_31_n));
defparam tdl_ff_31_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_32_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_31_n),.data_out(tdl_dat_32_ch_0_n));
defparam tdl_ff_32_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_32_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_32_ch_0_n),.data_out(tdl_dat_32_n));
defparam tdl_ff_32_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_33_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_32_n),.data_out(tdl_dat_33_ch_0_n));
defparam tdl_ff_33_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_33_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_33_ch_0_n),.data_out(tdl_dat_33_n));
defparam tdl_ff_33_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_34_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_33_n),.data_out(tdl_dat_34_ch_0_n));
defparam tdl_ff_34_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_34_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_34_ch_0_n),.data_out(tdl_dat_34_n));
defparam tdl_ff_34_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_35_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_34_n),.data_out(tdl_dat_35_ch_0_n));
defparam tdl_ff_35_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_35_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_35_ch_0_n),.data_out(tdl_dat_35_n));
defparam tdl_ff_35_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_36_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_35_n),.data_out(tdl_dat_36_ch_0_n));
defparam tdl_ff_36_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_36_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_36_ch_0_n),.data_out(tdl_dat_36_n));
defparam tdl_ff_36_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_37_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_36_n),.data_out(tdl_dat_37_ch_0_n));
defparam tdl_ff_37_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_37_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_37_ch_0_n),.data_out(tdl_dat_37_n));
defparam tdl_ff_37_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_38_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_37_n),.data_out(tdl_dat_38_ch_0_n));
defparam tdl_ff_38_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_38_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_38_ch_0_n),.data_out(tdl_dat_38_n));
defparam tdl_ff_38_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_39_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_38_n),.data_out(tdl_dat_39_ch_0_n));
defparam tdl_ff_39_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_39_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_39_ch_0_n),.data_out(tdl_dat_39_n));
defparam tdl_ff_39_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_40_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_39_n),.data_out(tdl_dat_40_ch_0_n));
defparam tdl_ff_40_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_40_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_40_ch_0_n),.data_out(tdl_dat_40_n));
defparam tdl_ff_40_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_41_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_40_n),.data_out(tdl_dat_41_ch_0_n));
defparam tdl_ff_41_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_41_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_41_ch_0_n),.data_out(tdl_dat_41_n));
defparam tdl_ff_41_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_42_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_41_n),.data_out(tdl_dat_42_ch_0_n));
defparam tdl_ff_42_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_42_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_42_ch_0_n),.data_out(tdl_dat_42_n));
defparam tdl_ff_42_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_43_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_42_n),.data_out(tdl_dat_43_ch_0_n));
defparam tdl_ff_43_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_43_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_43_ch_0_n),.data_out(tdl_dat_43_n));
defparam tdl_ff_43_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_44_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_43_n),.data_out(tdl_dat_44_ch_0_n));
defparam tdl_ff_44_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_44_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_44_ch_0_n),.data_out(tdl_dat_44_n));
defparam tdl_ff_44_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_45_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_44_n),.data_out(tdl_dat_45_ch_0_n));
defparam tdl_ff_45_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_45_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_45_ch_0_n),.data_out(tdl_dat_45_n));
defparam tdl_ff_45_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_46_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_45_n),.data_out(tdl_dat_46_ch_0_n));
defparam tdl_ff_46_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_46_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_46_ch_0_n),.data_out(tdl_dat_46_n));
defparam tdl_ff_46_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_47_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_46_n),.data_out(tdl_dat_47_ch_0_n));
defparam tdl_ff_47_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_47_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_47_ch_0_n),.data_out(tdl_dat_47_n));
defparam tdl_ff_47_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_48_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_47_n),.data_out(tdl_dat_48_ch_0_n));
defparam tdl_ff_48_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_48_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_48_ch_0_n),.data_out(tdl_dat_48_n));
defparam tdl_ff_48_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_49_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_48_n),.data_out(tdl_dat_49_ch_0_n));
defparam tdl_ff_49_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_49_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_49_ch_0_n),.data_out(tdl_dat_49_n));
defparam tdl_ff_49_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_50_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_49_n),.data_out(tdl_dat_50_ch_0_n));
defparam tdl_ff_50_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_50_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_50_ch_0_n),.data_out(tdl_dat_50_n));
defparam tdl_ff_50_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_51_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_50_n),.data_out(tdl_dat_51_ch_0_n));
defparam tdl_ff_51_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_51_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_51_ch_0_n),.data_out(tdl_dat_51_n));
defparam tdl_ff_51_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_52_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_51_n),.data_out(tdl_dat_52_ch_0_n));
defparam tdl_ff_52_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_52_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_52_ch_0_n),.data_out(tdl_dat_52_n));
defparam tdl_ff_52_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_53_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_52_n),.data_out(tdl_dat_53_ch_0_n));
defparam tdl_ff_53_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_53_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_53_ch_0_n),.data_out(tdl_dat_53_n));
defparam tdl_ff_53_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_54_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_53_n),.data_out(tdl_dat_54_ch_0_n));
defparam tdl_ff_54_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_54_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_54_ch_0_n),.data_out(tdl_dat_54_n));
defparam tdl_ff_54_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_55_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_54_n),.data_out(tdl_dat_55_ch_0_n));
defparam tdl_ff_55_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_55_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_55_ch_0_n),.data_out(tdl_dat_55_n));
defparam tdl_ff_55_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_56_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_55_n),.data_out(tdl_dat_56_ch_0_n));
defparam tdl_ff_56_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_56_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_56_ch_0_n),.data_out(tdl_dat_56_n));
defparam tdl_ff_56_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_57_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_56_n),.data_out(tdl_dat_57_ch_0_n));
defparam tdl_ff_57_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_57_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_57_ch_0_n),.data_out(tdl_dat_57_n));
defparam tdl_ff_57_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_58_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_57_n),.data_out(tdl_dat_58_ch_0_n));
defparam tdl_ff_58_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_58_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_58_ch_0_n),.data_out(tdl_dat_58_n));
defparam tdl_ff_58_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_59_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_58_n),.data_out(tdl_dat_59_ch_0_n));
defparam tdl_ff_59_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_59_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_59_ch_0_n),.data_out(tdl_dat_59_n));
defparam tdl_ff_59_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_60_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_59_n),.data_out(tdl_dat_60_ch_0_n));
defparam tdl_ff_60_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_60_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_60_ch_0_n),.data_out(tdl_dat_60_n));
defparam tdl_ff_60_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_61_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_60_n),.data_out(tdl_dat_61_ch_0_n));
defparam tdl_ff_61_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_61_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_61_ch_0_n),.data_out(tdl_dat_61_n));
defparam tdl_ff_61_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_62_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_61_n),.data_out(tdl_dat_62_ch_0_n));
defparam tdl_ff_62_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_62_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_62_ch_0_n),.data_out(tdl_dat_62_n));
defparam tdl_ff_62_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_63_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_62_n),.data_out(tdl_dat_63_ch_0_n));
defparam tdl_ff_63_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_63_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_63_ch_0_n),.data_out(tdl_dat_63_n));
defparam tdl_ff_63_ch_1_n.WIDTH = 16;
tdl_da_lc tdl_ff_64_ch_0_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_63_n),.data_out(tdl_dat_64_ch_0_n));
defparam tdl_ff_64_ch_0_n.WIDTH = 16;
tdl_da_lc tdl_ff_64_ch_1_n(.clk(clk), .clk_en(clk_en),.rst(rst),.data_in(tdl_dat_64_ch_0_n),.data_out(tdl_dat_64_n));
defparam tdl_ff_64_ch_1_n.WIDTH = 16;

wire coef_en ;
assign coef_en = clk_en;
wire [15:0] coef_st_comb_0_n;
wire [COEF_WIDTH-1:0]coef_st_0_n;
assign coef_st_0_n = coef_st_comb_0_n[15:0];
msft_lt_32 Ucoef_0_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_0_n));
defparam Ucoef_0_n.WIDTH = COEF_WIDTH;
defparam Ucoef_0_n.LENGTH = 1;
defparam Ucoef_0_n.DELAY = 0;
defparam Ucoef_0_n.C0 = 65464;
wire [15:0] coef_st_comb_1_n;
wire [COEF_WIDTH-1:0]coef_st_1_n;
assign coef_st_1_n = coef_st_comb_1_n[15:0];
msft_lt_32 Ucoef_1_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_1_n));
defparam Ucoef_1_n.WIDTH = COEF_WIDTH;
defparam Ucoef_1_n.LENGTH = 1;
defparam Ucoef_1_n.DELAY = 0;
defparam Ucoef_1_n.C0 = 65397;
wire [15:0] coef_st_comb_2_n;
wire [COEF_WIDTH-1:0]coef_st_2_n;
assign coef_st_2_n = coef_st_comb_2_n[15:0];
msft_lt_32 Ucoef_2_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_2_n));
defparam Ucoef_2_n.WIDTH = COEF_WIDTH;
defparam Ucoef_2_n.LENGTH = 1;
defparam Ucoef_2_n.DELAY = 0;
defparam Ucoef_2_n.C0 = 65341;
wire [15:0] coef_st_comb_3_n;
wire [COEF_WIDTH-1:0]coef_st_3_n;
assign coef_st_3_n = coef_st_comb_3_n[15:0];
msft_lt_32 Ucoef_3_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_3_n));
defparam Ucoef_3_n.WIDTH = COEF_WIDTH;
defparam Ucoef_3_n.LENGTH = 1;
defparam Ucoef_3_n.DELAY = 0;
defparam Ucoef_3_n.C0 = 65339;
wire [15:0] coef_st_comb_4_n;
wire [COEF_WIDTH-1:0]coef_st_4_n;
assign coef_st_4_n = coef_st_comb_4_n[15:0];
msft_lt_32 Ucoef_4_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_4_n));
defparam Ucoef_4_n.WIDTH = COEF_WIDTH;
defparam Ucoef_4_n.LENGTH = 1;
defparam Ucoef_4_n.DELAY = 0;
defparam Ucoef_4_n.C0 = 65443;
wire [15:0] coef_st_comb_5_n;
wire [COEF_WIDTH-1:0]coef_st_5_n;
assign coef_st_5_n = coef_st_comb_5_n[15:0];
msft_lt_32 Ucoef_5_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_5_n));
defparam Ucoef_5_n.WIDTH = COEF_WIDTH;
defparam Ucoef_5_n.LENGTH = 1;
defparam Ucoef_5_n.DELAY = 0;
defparam Ucoef_5_n.C0 = 172;
wire [15:0] coef_st_comb_6_n;
wire [COEF_WIDTH-1:0]coef_st_6_n;
assign coef_st_6_n = coef_st_comb_6_n[15:0];
msft_lt_32 Ucoef_6_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_6_n));
defparam Ucoef_6_n.WIDTH = COEF_WIDTH;
defparam Ucoef_6_n.LENGTH = 1;
defparam Ucoef_6_n.DELAY = 0;
defparam Ucoef_6_n.C0 = 644;
wire [15:0] coef_st_comb_7_n;
wire [COEF_WIDTH-1:0]coef_st_7_n;
assign coef_st_7_n = coef_st_comb_7_n[15:0];
msft_lt_32 Ucoef_7_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_7_n));
defparam Ucoef_7_n.WIDTH = COEF_WIDTH;
defparam Ucoef_7_n.LENGTH = 1;
defparam Ucoef_7_n.DELAY = 0;
defparam Ucoef_7_n.C0 = 1340;
wire [15:0] coef_st_comb_8_n;
wire [COEF_WIDTH-1:0]coef_st_8_n;
assign coef_st_8_n = coef_st_comb_8_n[15:0];
msft_lt_32 Ucoef_8_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_8_n));
defparam Ucoef_8_n.WIDTH = COEF_WIDTH;
defparam Ucoef_8_n.LENGTH = 1;
defparam Ucoef_8_n.DELAY = 0;
defparam Ucoef_8_n.C0 = 2233;
wire [15:0] coef_st_comb_9_n;
wire [COEF_WIDTH-1:0]coef_st_9_n;
assign coef_st_9_n = coef_st_comb_9_n[15:0];
msft_lt_32 Ucoef_9_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_9_n));
defparam Ucoef_9_n.WIDTH = COEF_WIDTH;
defparam Ucoef_9_n.LENGTH = 1;
defparam Ucoef_9_n.DELAY = 0;
defparam Ucoef_9_n.C0 = 3239;
wire [15:0] coef_st_comb_10_n;
wire [COEF_WIDTH-1:0]coef_st_10_n;
assign coef_st_10_n = coef_st_comb_10_n[15:0];
msft_lt_32 Ucoef_10_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_10_n));
defparam Ucoef_10_n.WIDTH = COEF_WIDTH;
defparam Ucoef_10_n.LENGTH = 1;
defparam Ucoef_10_n.DELAY = 0;
defparam Ucoef_10_n.C0 = 4215;
wire [15:0] coef_st_comb_11_n;
wire [COEF_WIDTH-1:0]coef_st_11_n;
assign coef_st_11_n = coef_st_comb_11_n[15:0];
msft_lt_32 Ucoef_11_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_11_n));
defparam Ucoef_11_n.WIDTH = COEF_WIDTH;
defparam Ucoef_11_n.LENGTH = 1;
defparam Ucoef_11_n.DELAY = 0;
defparam Ucoef_11_n.C0 = 4962;
wire [15:0] coef_st_comb_12_n;
wire [COEF_WIDTH-1:0]coef_st_12_n;
assign coef_st_12_n = coef_st_comb_12_n[15:0];
msft_lt_32 Ucoef_12_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_12_n));
defparam Ucoef_12_n.WIDTH = COEF_WIDTH;
defparam Ucoef_12_n.LENGTH = 1;
defparam Ucoef_12_n.DELAY = 0;
defparam Ucoef_12_n.C0 = 5253;
wire [15:0] coef_st_comb_13_n;
wire [COEF_WIDTH-1:0]coef_st_13_n;
assign coef_st_13_n = coef_st_comb_13_n[15:0];
msft_lt_32 Ucoef_13_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_13_n));
defparam Ucoef_13_n.WIDTH = COEF_WIDTH;
defparam Ucoef_13_n.LENGTH = 1;
defparam Ucoef_13_n.DELAY = 0;
defparam Ucoef_13_n.C0 = 4858;
wire [15:0] coef_st_comb_14_n;
wire [COEF_WIDTH-1:0]coef_st_14_n;
assign coef_st_14_n = coef_st_comb_14_n[15:0];
msft_lt_32 Ucoef_14_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_14_n));
defparam Ucoef_14_n.WIDTH = COEF_WIDTH;
defparam Ucoef_14_n.LENGTH = 1;
defparam Ucoef_14_n.DELAY = 0;
defparam Ucoef_14_n.C0 = 3592;
wire [15:0] coef_st_comb_15_n;
wire [COEF_WIDTH-1:0]coef_st_15_n;
assign coef_st_15_n = coef_st_comb_15_n[15:0];
msft_lt_32 Ucoef_15_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_15_n));
defparam Ucoef_15_n.WIDTH = COEF_WIDTH;
defparam Ucoef_15_n.LENGTH = 1;
defparam Ucoef_15_n.DELAY = 0;
defparam Ucoef_15_n.C0 = 1358;
wire [15:0] coef_st_comb_16_n;
wire [COEF_WIDTH-1:0]coef_st_16_n;
assign coef_st_16_n = coef_st_comb_16_n[15:0];
msft_lt_32 Ucoef_16_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_16_n));
defparam Ucoef_16_n.WIDTH = COEF_WIDTH;
defparam Ucoef_16_n.LENGTH = 1;
defparam Ucoef_16_n.DELAY = 0;
defparam Ucoef_16_n.C0 = 63721;
wire [15:0] coef_st_comb_17_n;
wire [COEF_WIDTH-1:0]coef_st_17_n;
assign coef_st_17_n = coef_st_comb_17_n[15:0];
msft_lt_32 Ucoef_17_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_17_n));
defparam Ucoef_17_n.WIDTH = COEF_WIDTH;
defparam Ucoef_17_n.LENGTH = 1;
defparam Ucoef_17_n.DELAY = 0;
defparam Ucoef_17_n.C0 = 59787;
wire [15:0] coef_st_comb_18_n;
wire [COEF_WIDTH-1:0]coef_st_18_n;
assign coef_st_18_n = coef_st_comb_18_n[15:0];
msft_lt_32 Ucoef_18_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_18_n));
defparam Ucoef_18_n.WIDTH = COEF_WIDTH;
defparam Ucoef_18_n.LENGTH = 1;
defparam Ucoef_18_n.DELAY = 0;
defparam Ucoef_18_n.C0 = 55430;
wire [15:0] coef_st_comb_19_n;
wire [COEF_WIDTH-1:0]coef_st_19_n;
assign coef_st_19_n = coef_st_comb_19_n[15:0];
msft_lt_32 Ucoef_19_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_19_n));
defparam Ucoef_19_n.WIDTH = COEF_WIDTH;
defparam Ucoef_19_n.LENGTH = 1;
defparam Ucoef_19_n.DELAY = 0;
defparam Ucoef_19_n.C0 = 51122;
wire [15:0] coef_st_comb_20_n;
wire [COEF_WIDTH-1:0]coef_st_20_n;
assign coef_st_20_n = coef_st_comb_20_n[15:0];
msft_lt_32 Ucoef_20_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_20_n));
defparam Ucoef_20_n.WIDTH = COEF_WIDTH;
defparam Ucoef_20_n.LENGTH = 1;
defparam Ucoef_20_n.DELAY = 0;
defparam Ucoef_20_n.C0 = 47422;
wire [15:0] coef_st_comb_21_n;
wire [COEF_WIDTH-1:0]coef_st_21_n;
assign coef_st_21_n = coef_st_comb_21_n[15:0];
msft_lt_32 Ucoef_21_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_21_n));
defparam Ucoef_21_n.WIDTH = COEF_WIDTH;
defparam Ucoef_21_n.LENGTH = 1;
defparam Ucoef_21_n.DELAY = 0;
defparam Ucoef_21_n.C0 = 44905;
wire [15:0] coef_st_comb_22_n;
wire [COEF_WIDTH-1:0]coef_st_22_n;
assign coef_st_22_n = coef_st_comb_22_n[15:0];
msft_lt_32 Ucoef_22_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_22_n));
defparam Ucoef_22_n.WIDTH = COEF_WIDTH;
defparam Ucoef_22_n.LENGTH = 1;
defparam Ucoef_22_n.DELAY = 0;
defparam Ucoef_22_n.C0 = 44086;
wire [15:0] coef_st_comb_23_n;
wire [COEF_WIDTH-1:0]coef_st_23_n;
assign coef_st_23_n = coef_st_comb_23_n[15:0];
msft_lt_32 Ucoef_23_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_23_n));
defparam Ucoef_23_n.WIDTH = COEF_WIDTH;
defparam Ucoef_23_n.LENGTH = 1;
defparam Ucoef_23_n.DELAY = 0;
defparam Ucoef_23_n.C0 = 45330;
wire [15:0] coef_st_comb_24_n;
wire [COEF_WIDTH-1:0]coef_st_24_n;
assign coef_st_24_n = coef_st_comb_24_n[15:0];
msft_lt_32 Ucoef_24_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_24_n));
defparam Ucoef_24_n.WIDTH = COEF_WIDTH;
defparam Ucoef_24_n.LENGTH = 1;
defparam Ucoef_24_n.DELAY = 0;
defparam Ucoef_24_n.C0 = 48782;
wire [15:0] coef_st_comb_25_n;
wire [COEF_WIDTH-1:0]coef_st_25_n;
assign coef_st_25_n = coef_st_comb_25_n[15:0];
msft_lt_32 Ucoef_25_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_25_n));
defparam Ucoef_25_n.WIDTH = COEF_WIDTH;
defparam Ucoef_25_n.LENGTH = 1;
defparam Ucoef_25_n.DELAY = 0;
defparam Ucoef_25_n.C0 = 54327;
wire [15:0] coef_st_comb_26_n;
wire [COEF_WIDTH-1:0]coef_st_26_n;
assign coef_st_26_n = coef_st_comb_26_n[15:0];
msft_lt_32 Ucoef_26_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_26_n));
defparam Ucoef_26_n.WIDTH = COEF_WIDTH;
defparam Ucoef_26_n.LENGTH = 1;
defparam Ucoef_26_n.DELAY = 0;
defparam Ucoef_26_n.C0 = 61572;
wire [15:0] coef_st_comb_27_n;
wire [COEF_WIDTH-1:0]coef_st_27_n;
assign coef_st_27_n = coef_st_comb_27_n[15:0];
msft_lt_32 Ucoef_27_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_27_n));
defparam Ucoef_27_n.WIDTH = COEF_WIDTH;
defparam Ucoef_27_n.LENGTH = 1;
defparam Ucoef_27_n.DELAY = 0;
defparam Ucoef_27_n.C0 = 4342;
wire [15:0] coef_st_comb_28_n;
wire [COEF_WIDTH-1:0]coef_st_28_n;
assign coef_st_28_n = coef_st_comb_28_n[15:0];
msft_lt_32 Ucoef_28_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_28_n));
defparam Ucoef_28_n.WIDTH = COEF_WIDTH;
defparam Ucoef_28_n.LENGTH = 1;
defparam Ucoef_28_n.DELAY = 0;
defparam Ucoef_28_n.C0 = 12895;
wire [15:0] coef_st_comb_29_n;
wire [COEF_WIDTH-1:0]coef_st_29_n;
assign coef_st_29_n = coef_st_comb_29_n[15:0];
msft_lt_32 Ucoef_29_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_29_n));
defparam Ucoef_29_n.WIDTH = COEF_WIDTH;
defparam Ucoef_29_n.LENGTH = 1;
defparam Ucoef_29_n.DELAY = 0;
defparam Ucoef_29_n.C0 = 20796;
wire [15:0] coef_st_comb_30_n;
wire [COEF_WIDTH-1:0]coef_st_30_n;
assign coef_st_30_n = coef_st_comb_30_n[15:0];
msft_lt_32 Ucoef_30_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_30_n));
defparam Ucoef_30_n.WIDTH = COEF_WIDTH;
defparam Ucoef_30_n.LENGTH = 1;
defparam Ucoef_30_n.DELAY = 0;
defparam Ucoef_30_n.C0 = 27180;
wire [15:0] coef_st_comb_31_n;
wire [COEF_WIDTH-1:0]coef_st_31_n;
assign coef_st_31_n = coef_st_comb_31_n[15:0];
msft_lt_32 Ucoef_31_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_31_n));
defparam Ucoef_31_n.WIDTH = COEF_WIDTH;
defparam Ucoef_31_n.LENGTH = 1;
defparam Ucoef_31_n.DELAY = 0;
defparam Ucoef_31_n.C0 = 31328;
wire [15:0] coef_st_comb_32_n;
wire [COEF_WIDTH-1:0]coef_st_32_n;
assign coef_st_32_n = coef_st_comb_32_n[15:0];
msft_lt_32 Ucoef_32_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_32_n));
defparam Ucoef_32_n.WIDTH = COEF_WIDTH;
defparam Ucoef_32_n.LENGTH = 1;
defparam Ucoef_32_n.DELAY = 0;
defparam Ucoef_32_n.C0 = 32767;
wire [15:0] coef_st_comb_33_n;
wire [COEF_WIDTH-1:0]coef_st_33_n;
assign coef_st_33_n = coef_st_comb_33_n[15:0];
msft_lt_32 Ucoef_33_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_33_n));
defparam Ucoef_33_n.WIDTH = COEF_WIDTH;
defparam Ucoef_33_n.LENGTH = 1;
defparam Ucoef_33_n.DELAY = 0;
defparam Ucoef_33_n.C0 = 31328;
wire [15:0] coef_st_comb_34_n;
wire [COEF_WIDTH-1:0]coef_st_34_n;
assign coef_st_34_n = coef_st_comb_34_n[15:0];
msft_lt_32 Ucoef_34_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_34_n));
defparam Ucoef_34_n.WIDTH = COEF_WIDTH;
defparam Ucoef_34_n.LENGTH = 1;
defparam Ucoef_34_n.DELAY = 0;
defparam Ucoef_34_n.C0 = 27180;
wire [15:0] coef_st_comb_35_n;
wire [COEF_WIDTH-1:0]coef_st_35_n;
assign coef_st_35_n = coef_st_comb_35_n[15:0];
msft_lt_32 Ucoef_35_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_35_n));
defparam Ucoef_35_n.WIDTH = COEF_WIDTH;
defparam Ucoef_35_n.LENGTH = 1;
defparam Ucoef_35_n.DELAY = 0;
defparam Ucoef_35_n.C0 = 20796;
wire [15:0] coef_st_comb_36_n;
wire [COEF_WIDTH-1:0]coef_st_36_n;
assign coef_st_36_n = coef_st_comb_36_n[15:0];
msft_lt_32 Ucoef_36_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_36_n));
defparam Ucoef_36_n.WIDTH = COEF_WIDTH;
defparam Ucoef_36_n.LENGTH = 1;
defparam Ucoef_36_n.DELAY = 0;
defparam Ucoef_36_n.C0 = 12895;
wire [15:0] coef_st_comb_37_n;
wire [COEF_WIDTH-1:0]coef_st_37_n;
assign coef_st_37_n = coef_st_comb_37_n[15:0];
msft_lt_32 Ucoef_37_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_37_n));
defparam Ucoef_37_n.WIDTH = COEF_WIDTH;
defparam Ucoef_37_n.LENGTH = 1;
defparam Ucoef_37_n.DELAY = 0;
defparam Ucoef_37_n.C0 = 4342;
wire [15:0] coef_st_comb_38_n;
wire [COEF_WIDTH-1:0]coef_st_38_n;
assign coef_st_38_n = coef_st_comb_38_n[15:0];
msft_lt_32 Ucoef_38_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_38_n));
defparam Ucoef_38_n.WIDTH = COEF_WIDTH;
defparam Ucoef_38_n.LENGTH = 1;
defparam Ucoef_38_n.DELAY = 0;
defparam Ucoef_38_n.C0 = 61572;
wire [15:0] coef_st_comb_39_n;
wire [COEF_WIDTH-1:0]coef_st_39_n;
assign coef_st_39_n = coef_st_comb_39_n[15:0];
msft_lt_32 Ucoef_39_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_39_n));
defparam Ucoef_39_n.WIDTH = COEF_WIDTH;
defparam Ucoef_39_n.LENGTH = 1;
defparam Ucoef_39_n.DELAY = 0;
defparam Ucoef_39_n.C0 = 54327;
wire [15:0] coef_st_comb_40_n;
wire [COEF_WIDTH-1:0]coef_st_40_n;
assign coef_st_40_n = coef_st_comb_40_n[15:0];
msft_lt_32 Ucoef_40_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_40_n));
defparam Ucoef_40_n.WIDTH = COEF_WIDTH;
defparam Ucoef_40_n.LENGTH = 1;
defparam Ucoef_40_n.DELAY = 0;
defparam Ucoef_40_n.C0 = 48782;
wire [15:0] coef_st_comb_41_n;
wire [COEF_WIDTH-1:0]coef_st_41_n;
assign coef_st_41_n = coef_st_comb_41_n[15:0];
msft_lt_32 Ucoef_41_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_41_n));
defparam Ucoef_41_n.WIDTH = COEF_WIDTH;
defparam Ucoef_41_n.LENGTH = 1;
defparam Ucoef_41_n.DELAY = 0;
defparam Ucoef_41_n.C0 = 45330;
wire [15:0] coef_st_comb_42_n;
wire [COEF_WIDTH-1:0]coef_st_42_n;
assign coef_st_42_n = coef_st_comb_42_n[15:0];
msft_lt_32 Ucoef_42_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_42_n));
defparam Ucoef_42_n.WIDTH = COEF_WIDTH;
defparam Ucoef_42_n.LENGTH = 1;
defparam Ucoef_42_n.DELAY = 0;
defparam Ucoef_42_n.C0 = 44086;
wire [15:0] coef_st_comb_43_n;
wire [COEF_WIDTH-1:0]coef_st_43_n;
assign coef_st_43_n = coef_st_comb_43_n[15:0];
msft_lt_32 Ucoef_43_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_43_n));
defparam Ucoef_43_n.WIDTH = COEF_WIDTH;
defparam Ucoef_43_n.LENGTH = 1;
defparam Ucoef_43_n.DELAY = 0;
defparam Ucoef_43_n.C0 = 44905;
wire [15:0] coef_st_comb_44_n;
wire [COEF_WIDTH-1:0]coef_st_44_n;
assign coef_st_44_n = coef_st_comb_44_n[15:0];
msft_lt_32 Ucoef_44_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_44_n));
defparam Ucoef_44_n.WIDTH = COEF_WIDTH;
defparam Ucoef_44_n.LENGTH = 1;
defparam Ucoef_44_n.DELAY = 0;
defparam Ucoef_44_n.C0 = 47422;
wire [15:0] coef_st_comb_45_n;
wire [COEF_WIDTH-1:0]coef_st_45_n;
assign coef_st_45_n = coef_st_comb_45_n[15:0];
msft_lt_32 Ucoef_45_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_45_n));
defparam Ucoef_45_n.WIDTH = COEF_WIDTH;
defparam Ucoef_45_n.LENGTH = 1;
defparam Ucoef_45_n.DELAY = 0;
defparam Ucoef_45_n.C0 = 51122;
wire [15:0] coef_st_comb_46_n;
wire [COEF_WIDTH-1:0]coef_st_46_n;
assign coef_st_46_n = coef_st_comb_46_n[15:0];
msft_lt_32 Ucoef_46_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_46_n));
defparam Ucoef_46_n.WIDTH = COEF_WIDTH;
defparam Ucoef_46_n.LENGTH = 1;
defparam Ucoef_46_n.DELAY = 0;
defparam Ucoef_46_n.C0 = 55430;
wire [15:0] coef_st_comb_47_n;
wire [COEF_WIDTH-1:0]coef_st_47_n;
assign coef_st_47_n = coef_st_comb_47_n[15:0];
msft_lt_32 Ucoef_47_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_47_n));
defparam Ucoef_47_n.WIDTH = COEF_WIDTH;
defparam Ucoef_47_n.LENGTH = 1;
defparam Ucoef_47_n.DELAY = 0;
defparam Ucoef_47_n.C0 = 59787;
wire [15:0] coef_st_comb_48_n;
wire [COEF_WIDTH-1:0]coef_st_48_n;
assign coef_st_48_n = coef_st_comb_48_n[15:0];
msft_lt_32 Ucoef_48_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_48_n));
defparam Ucoef_48_n.WIDTH = COEF_WIDTH;
defparam Ucoef_48_n.LENGTH = 1;
defparam Ucoef_48_n.DELAY = 0;
defparam Ucoef_48_n.C0 = 63721;
wire [15:0] coef_st_comb_49_n;
wire [COEF_WIDTH-1:0]coef_st_49_n;
assign coef_st_49_n = coef_st_comb_49_n[15:0];
msft_lt_32 Ucoef_49_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_49_n));
defparam Ucoef_49_n.WIDTH = COEF_WIDTH;
defparam Ucoef_49_n.LENGTH = 1;
defparam Ucoef_49_n.DELAY = 0;
defparam Ucoef_49_n.C0 = 1358;
wire [15:0] coef_st_comb_50_n;
wire [COEF_WIDTH-1:0]coef_st_50_n;
assign coef_st_50_n = coef_st_comb_50_n[15:0];
msft_lt_32 Ucoef_50_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_50_n));
defparam Ucoef_50_n.WIDTH = COEF_WIDTH;
defparam Ucoef_50_n.LENGTH = 1;
defparam Ucoef_50_n.DELAY = 0;
defparam Ucoef_50_n.C0 = 3592;
wire [15:0] coef_st_comb_51_n;
wire [COEF_WIDTH-1:0]coef_st_51_n;
assign coef_st_51_n = coef_st_comb_51_n[15:0];
msft_lt_32 Ucoef_51_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_51_n));
defparam Ucoef_51_n.WIDTH = COEF_WIDTH;
defparam Ucoef_51_n.LENGTH = 1;
defparam Ucoef_51_n.DELAY = 0;
defparam Ucoef_51_n.C0 = 4858;
wire [15:0] coef_st_comb_52_n;
wire [COEF_WIDTH-1:0]coef_st_52_n;
assign coef_st_52_n = coef_st_comb_52_n[15:0];
msft_lt_32 Ucoef_52_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_52_n));
defparam Ucoef_52_n.WIDTH = COEF_WIDTH;
defparam Ucoef_52_n.LENGTH = 1;
defparam Ucoef_52_n.DELAY = 0;
defparam Ucoef_52_n.C0 = 5253;
wire [15:0] coef_st_comb_53_n;
wire [COEF_WIDTH-1:0]coef_st_53_n;
assign coef_st_53_n = coef_st_comb_53_n[15:0];
msft_lt_32 Ucoef_53_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_53_n));
defparam Ucoef_53_n.WIDTH = COEF_WIDTH;
defparam Ucoef_53_n.LENGTH = 1;
defparam Ucoef_53_n.DELAY = 0;
defparam Ucoef_53_n.C0 = 4962;
wire [15:0] coef_st_comb_54_n;
wire [COEF_WIDTH-1:0]coef_st_54_n;
assign coef_st_54_n = coef_st_comb_54_n[15:0];
msft_lt_32 Ucoef_54_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_54_n));
defparam Ucoef_54_n.WIDTH = COEF_WIDTH;
defparam Ucoef_54_n.LENGTH = 1;
defparam Ucoef_54_n.DELAY = 0;
defparam Ucoef_54_n.C0 = 4215;
wire [15:0] coef_st_comb_55_n;
wire [COEF_WIDTH-1:0]coef_st_55_n;
assign coef_st_55_n = coef_st_comb_55_n[15:0];
msft_lt_32 Ucoef_55_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_55_n));
defparam Ucoef_55_n.WIDTH = COEF_WIDTH;
defparam Ucoef_55_n.LENGTH = 1;
defparam Ucoef_55_n.DELAY = 0;
defparam Ucoef_55_n.C0 = 3239;
wire [15:0] coef_st_comb_56_n;
wire [COEF_WIDTH-1:0]coef_st_56_n;
assign coef_st_56_n = coef_st_comb_56_n[15:0];
msft_lt_32 Ucoef_56_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_56_n));
defparam Ucoef_56_n.WIDTH = COEF_WIDTH;
defparam Ucoef_56_n.LENGTH = 1;
defparam Ucoef_56_n.DELAY = 0;
defparam Ucoef_56_n.C0 = 2233;
wire [15:0] coef_st_comb_57_n;
wire [COEF_WIDTH-1:0]coef_st_57_n;
assign coef_st_57_n = coef_st_comb_57_n[15:0];
msft_lt_32 Ucoef_57_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_57_n));
defparam Ucoef_57_n.WIDTH = COEF_WIDTH;
defparam Ucoef_57_n.LENGTH = 1;
defparam Ucoef_57_n.DELAY = 0;
defparam Ucoef_57_n.C0 = 1340;
wire [15:0] coef_st_comb_58_n;
wire [COEF_WIDTH-1:0]coef_st_58_n;
assign coef_st_58_n = coef_st_comb_58_n[15:0];
msft_lt_32 Ucoef_58_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_58_n));
defparam Ucoef_58_n.WIDTH = COEF_WIDTH;
defparam Ucoef_58_n.LENGTH = 1;
defparam Ucoef_58_n.DELAY = 0;
defparam Ucoef_58_n.C0 = 644;
wire [15:0] coef_st_comb_59_n;
wire [COEF_WIDTH-1:0]coef_st_59_n;
assign coef_st_59_n = coef_st_comb_59_n[15:0];
msft_lt_32 Ucoef_59_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_59_n));
defparam Ucoef_59_n.WIDTH = COEF_WIDTH;
defparam Ucoef_59_n.LENGTH = 1;
defparam Ucoef_59_n.DELAY = 0;
defparam Ucoef_59_n.C0 = 172;
wire [15:0] coef_st_comb_60_n;
wire [COEF_WIDTH-1:0]coef_st_60_n;
assign coef_st_60_n = coef_st_comb_60_n[15:0];
msft_lt_32 Ucoef_60_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_60_n));
defparam Ucoef_60_n.WIDTH = COEF_WIDTH;
defparam Ucoef_60_n.LENGTH = 1;
defparam Ucoef_60_n.DELAY = 0;
defparam Ucoef_60_n.C0 = 65443;
wire [15:0] coef_st_comb_61_n;
wire [COEF_WIDTH-1:0]coef_st_61_n;
assign coef_st_61_n = coef_st_comb_61_n[15:0];
msft_lt_32 Ucoef_61_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_61_n));
defparam Ucoef_61_n.WIDTH = COEF_WIDTH;
defparam Ucoef_61_n.LENGTH = 1;
defparam Ucoef_61_n.DELAY = 0;
defparam Ucoef_61_n.C0 = 65339;
wire [15:0] coef_st_comb_62_n;
wire [COEF_WIDTH-1:0]coef_st_62_n;
assign coef_st_62_n = coef_st_comb_62_n[15:0];
msft_lt_32 Ucoef_62_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_62_n));
defparam Ucoef_62_n.WIDTH = COEF_WIDTH;
defparam Ucoef_62_n.LENGTH = 1;
defparam Ucoef_62_n.DELAY = 0;
defparam Ucoef_62_n.C0 = 65341;
wire [15:0] coef_st_comb_63_n;
wire [COEF_WIDTH-1:0]coef_st_63_n;
assign coef_st_63_n = coef_st_comb_63_n[15:0];
msft_lt_32 Ucoef_63_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_63_n));
defparam Ucoef_63_n.WIDTH = COEF_WIDTH;
defparam Ucoef_63_n.LENGTH = 1;
defparam Ucoef_63_n.DELAY = 0;
defparam Ucoef_63_n.C0 = 65397;
wire [15:0] coef_st_comb_64_n;
wire [COEF_WIDTH-1:0]coef_st_64_n;
assign coef_st_64_n = coef_st_comb_64_n[15:0];
msft_lt_32 Ucoef_64_n (.rst(rst), .clk(clk), .clk_en(coef_en), .we(1'b0), .data_in(16'b0), .data_out(coef_st_comb_64_n));
defparam Ucoef_64_n.WIDTH = COEF_WIDTH;
defparam Ucoef_64_n.LENGTH = 1;
defparam Ucoef_64_n.DELAY = 0;
defparam Ucoef_64_n.C0 = 65464;


wire [31:0] mlu_resx_0_n;
mlu_inf_2reg Umlu_0_n (.clk(clk), .data_in(tdl_dat_0_n), .coef_in(coef_st_0_n), .clk_en(clk_en), .mlu_out(mlu_resx_0_n) );
defparam Umlu_0_n.DATA_WIDTH = 16;
defparam Umlu_0_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_0_n.PIPE = 2;
defparam Umlu_0_n.DSP_USE = "YES";
wire [31:0] mlu_res_0_n;
mac_tl Umtl_0_n             (.clk(clk), 
             .data_in(mlu_resx_0_n),
             .data_out(mlu_res_0_n));
defparam Umtl_0_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_1_n;
mlu_inf_2reg Umlu_1_n (.clk(clk), .data_in(tdl_dat_1_n), .coef_in(coef_st_1_n), .clk_en(clk_en), .mlu_out(mlu_resx_1_n) );
defparam Umlu_1_n.DATA_WIDTH = 16;
defparam Umlu_1_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_1_n.PIPE = 2;
defparam Umlu_1_n.DSP_USE = "YES";
wire [31:0] mlu_res_1_n;
mac_tl Umtl_1_n             (.clk(clk), 
             .data_in(mlu_resx_1_n),
             .data_out(mlu_res_1_n));
defparam Umtl_1_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_2_n;
mlu_inf_2reg Umlu_2_n (.clk(clk), .data_in(tdl_dat_2_n), .coef_in(coef_st_2_n), .clk_en(clk_en), .mlu_out(mlu_resx_2_n) );
defparam Umlu_2_n.DATA_WIDTH = 16;
defparam Umlu_2_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_2_n.PIPE = 2;
defparam Umlu_2_n.DSP_USE = "YES";
wire [31:0] mlu_res_2_n;
mac_tl Umtl_2_n             (.clk(clk), 
             .data_in(mlu_resx_2_n),
             .data_out(mlu_res_2_n));
defparam Umtl_2_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_3_n;
mlu_inf_2reg Umlu_3_n (.clk(clk), .data_in(tdl_dat_3_n), .coef_in(coef_st_3_n), .clk_en(clk_en), .mlu_out(mlu_resx_3_n) );
defparam Umlu_3_n.DATA_WIDTH = 16;
defparam Umlu_3_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_3_n.PIPE = 2;
defparam Umlu_3_n.DSP_USE = "YES";
wire [31:0] mlu_res_3_n;
mac_tl Umtl_3_n             (.clk(clk), 
             .data_in(mlu_resx_3_n),
             .data_out(mlu_res_3_n));
defparam Umtl_3_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_4_n;
mlu_inf_2reg Umlu_4_n (.clk(clk), .data_in(tdl_dat_4_n), .coef_in(coef_st_4_n), .clk_en(clk_en), .mlu_out(mlu_resx_4_n) );
defparam Umlu_4_n.DATA_WIDTH = 16;
defparam Umlu_4_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_4_n.PIPE = 2;
defparam Umlu_4_n.DSP_USE = "YES";
wire [31:0] mlu_res_4_n;
mac_tl Umtl_4_n             (.clk(clk), 
             .data_in(mlu_resx_4_n),
             .data_out(mlu_res_4_n));
defparam Umtl_4_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_5_n;
mlu_inf_2reg Umlu_5_n (.clk(clk), .data_in(tdl_dat_5_n), .coef_in(coef_st_5_n), .clk_en(clk_en), .mlu_out(mlu_resx_5_n) );
defparam Umlu_5_n.DATA_WIDTH = 16;
defparam Umlu_5_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_5_n.PIPE = 2;
defparam Umlu_5_n.DSP_USE = "YES";
wire [31:0] mlu_res_5_n;
mac_tl Umtl_5_n             (.clk(clk), 
             .data_in(mlu_resx_5_n),
             .data_out(mlu_res_5_n));
defparam Umtl_5_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_6_n;
mlu_inf_2reg Umlu_6_n (.clk(clk), .data_in(tdl_dat_6_n), .coef_in(coef_st_6_n), .clk_en(clk_en), .mlu_out(mlu_resx_6_n) );
defparam Umlu_6_n.DATA_WIDTH = 16;
defparam Umlu_6_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_6_n.PIPE = 2;
defparam Umlu_6_n.DSP_USE = "YES";
wire [31:0] mlu_res_6_n;
mac_tl Umtl_6_n             (.clk(clk), 
             .data_in(mlu_resx_6_n),
             .data_out(mlu_res_6_n));
defparam Umtl_6_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_7_n;
mlu_inf_2reg Umlu_7_n (.clk(clk), .data_in(tdl_dat_7_n), .coef_in(coef_st_7_n), .clk_en(clk_en), .mlu_out(mlu_resx_7_n) );
defparam Umlu_7_n.DATA_WIDTH = 16;
defparam Umlu_7_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_7_n.PIPE = 2;
defparam Umlu_7_n.DSP_USE = "YES";
wire [31:0] mlu_res_7_n;
mac_tl Umtl_7_n             (.clk(clk), 
             .data_in(mlu_resx_7_n),
             .data_out(mlu_res_7_n));
defparam Umtl_7_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_8_n;
mlu_inf_2reg Umlu_8_n (.clk(clk), .data_in(tdl_dat_8_n), .coef_in(coef_st_8_n), .clk_en(clk_en), .mlu_out(mlu_resx_8_n) );
defparam Umlu_8_n.DATA_WIDTH = 16;
defparam Umlu_8_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_8_n.PIPE = 2;
defparam Umlu_8_n.DSP_USE = "YES";
wire [31:0] mlu_res_8_n;
mac_tl Umtl_8_n             (.clk(clk), 
             .data_in(mlu_resx_8_n),
             .data_out(mlu_res_8_n));
defparam Umtl_8_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_9_n;
mlu_inf_2reg Umlu_9_n (.clk(clk), .data_in(tdl_dat_9_n), .coef_in(coef_st_9_n), .clk_en(clk_en), .mlu_out(mlu_resx_9_n) );
defparam Umlu_9_n.DATA_WIDTH = 16;
defparam Umlu_9_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_9_n.PIPE = 2;
defparam Umlu_9_n.DSP_USE = "YES";
wire [31:0] mlu_res_9_n;
mac_tl Umtl_9_n             (.clk(clk), 
             .data_in(mlu_resx_9_n),
             .data_out(mlu_res_9_n));
defparam Umtl_9_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_10_n;
mlu_inf_2reg Umlu_10_n (.clk(clk), .data_in(tdl_dat_10_n), .coef_in(coef_st_10_n), .clk_en(clk_en), .mlu_out(mlu_resx_10_n) );
defparam Umlu_10_n.DATA_WIDTH = 16;
defparam Umlu_10_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_10_n.PIPE = 2;
defparam Umlu_10_n.DSP_USE = "YES";
wire [31:0] mlu_res_10_n;
mac_tl Umtl_10_n             (.clk(clk), 
             .data_in(mlu_resx_10_n),
             .data_out(mlu_res_10_n));
defparam Umtl_10_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_11_n;
mlu_inf_2reg Umlu_11_n (.clk(clk), .data_in(tdl_dat_11_n), .coef_in(coef_st_11_n), .clk_en(clk_en), .mlu_out(mlu_resx_11_n) );
defparam Umlu_11_n.DATA_WIDTH = 16;
defparam Umlu_11_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_11_n.PIPE = 2;
defparam Umlu_11_n.DSP_USE = "YES";
wire [31:0] mlu_res_11_n;
mac_tl Umtl_11_n             (.clk(clk), 
             .data_in(mlu_resx_11_n),
             .data_out(mlu_res_11_n));
defparam Umtl_11_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_12_n;
mlu_inf_2reg Umlu_12_n (.clk(clk), .data_in(tdl_dat_12_n), .coef_in(coef_st_12_n), .clk_en(clk_en), .mlu_out(mlu_resx_12_n) );
defparam Umlu_12_n.DATA_WIDTH = 16;
defparam Umlu_12_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_12_n.PIPE = 2;
defparam Umlu_12_n.DSP_USE = "YES";
wire [31:0] mlu_res_12_n;
mac_tl Umtl_12_n             (.clk(clk), 
             .data_in(mlu_resx_12_n),
             .data_out(mlu_res_12_n));
defparam Umtl_12_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_13_n;
mlu_inf_2reg Umlu_13_n (.clk(clk), .data_in(tdl_dat_13_n), .coef_in(coef_st_13_n), .clk_en(clk_en), .mlu_out(mlu_resx_13_n) );
defparam Umlu_13_n.DATA_WIDTH = 16;
defparam Umlu_13_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_13_n.PIPE = 2;
defparam Umlu_13_n.DSP_USE = "YES";
wire [31:0] mlu_res_13_n;
mac_tl Umtl_13_n             (.clk(clk), 
             .data_in(mlu_resx_13_n),
             .data_out(mlu_res_13_n));
defparam Umtl_13_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_14_n;
mlu_inf_2reg Umlu_14_n (.clk(clk), .data_in(tdl_dat_14_n), .coef_in(coef_st_14_n), .clk_en(clk_en), .mlu_out(mlu_resx_14_n) );
defparam Umlu_14_n.DATA_WIDTH = 16;
defparam Umlu_14_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_14_n.PIPE = 2;
defparam Umlu_14_n.DSP_USE = "YES";
wire [31:0] mlu_res_14_n;
mac_tl Umtl_14_n             (.clk(clk), 
             .data_in(mlu_resx_14_n),
             .data_out(mlu_res_14_n));
defparam Umtl_14_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_15_n;
mlu_inf_2reg Umlu_15_n (.clk(clk), .data_in(tdl_dat_15_n), .coef_in(coef_st_15_n), .clk_en(clk_en), .mlu_out(mlu_resx_15_n) );
defparam Umlu_15_n.DATA_WIDTH = 16;
defparam Umlu_15_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_15_n.PIPE = 2;
defparam Umlu_15_n.DSP_USE = "YES";
wire [31:0] mlu_res_15_n;
mac_tl Umtl_15_n             (.clk(clk), 
             .data_in(mlu_resx_15_n),
             .data_out(mlu_res_15_n));
defparam Umtl_15_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_16_n;
mlu_inf_2reg Umlu_16_n (.clk(clk), .data_in(tdl_dat_16_n), .coef_in(coef_st_16_n), .clk_en(clk_en), .mlu_out(mlu_resx_16_n) );
defparam Umlu_16_n.DATA_WIDTH = 16;
defparam Umlu_16_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_16_n.PIPE = 2;
defparam Umlu_16_n.DSP_USE = "YES";
wire [31:0] mlu_res_16_n;
mac_tl Umtl_16_n             (.clk(clk), 
             .data_in(mlu_resx_16_n),
             .data_out(mlu_res_16_n));
defparam Umtl_16_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_17_n;
mlu_inf_2reg Umlu_17_n (.clk(clk), .data_in(tdl_dat_17_n), .coef_in(coef_st_17_n), .clk_en(clk_en), .mlu_out(mlu_resx_17_n) );
defparam Umlu_17_n.DATA_WIDTH = 16;
defparam Umlu_17_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_17_n.PIPE = 2;
defparam Umlu_17_n.DSP_USE = "YES";
wire [31:0] mlu_res_17_n;
mac_tl Umtl_17_n             (.clk(clk), 
             .data_in(mlu_resx_17_n),
             .data_out(mlu_res_17_n));
defparam Umtl_17_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_18_n;
mlu_inf_2reg Umlu_18_n (.clk(clk), .data_in(tdl_dat_18_n), .coef_in(coef_st_18_n), .clk_en(clk_en), .mlu_out(mlu_resx_18_n) );
defparam Umlu_18_n.DATA_WIDTH = 16;
defparam Umlu_18_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_18_n.PIPE = 2;
defparam Umlu_18_n.DSP_USE = "YES";
wire [31:0] mlu_res_18_n;
mac_tl Umtl_18_n             (.clk(clk), 
             .data_in(mlu_resx_18_n),
             .data_out(mlu_res_18_n));
defparam Umtl_18_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_19_n;
mlu_inf_2reg Umlu_19_n (.clk(clk), .data_in(tdl_dat_19_n), .coef_in(coef_st_19_n), .clk_en(clk_en), .mlu_out(mlu_resx_19_n) );
defparam Umlu_19_n.DATA_WIDTH = 16;
defparam Umlu_19_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_19_n.PIPE = 2;
defparam Umlu_19_n.DSP_USE = "YES";
wire [31:0] mlu_res_19_n;
mac_tl Umtl_19_n             (.clk(clk), 
             .data_in(mlu_resx_19_n),
             .data_out(mlu_res_19_n));
defparam Umtl_19_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_20_n;
mlu_inf_2reg Umlu_20_n (.clk(clk), .data_in(tdl_dat_20_n), .coef_in(coef_st_20_n), .clk_en(clk_en), .mlu_out(mlu_resx_20_n) );
defparam Umlu_20_n.DATA_WIDTH = 16;
defparam Umlu_20_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_20_n.PIPE = 2;
defparam Umlu_20_n.DSP_USE = "YES";
wire [31:0] mlu_res_20_n;
mac_tl Umtl_20_n             (.clk(clk), 
             .data_in(mlu_resx_20_n),
             .data_out(mlu_res_20_n));
defparam Umtl_20_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_21_n;
mlu_inf_2reg Umlu_21_n (.clk(clk), .data_in(tdl_dat_21_n), .coef_in(coef_st_21_n), .clk_en(clk_en), .mlu_out(mlu_resx_21_n) );
defparam Umlu_21_n.DATA_WIDTH = 16;
defparam Umlu_21_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_21_n.PIPE = 2;
defparam Umlu_21_n.DSP_USE = "YES";
wire [31:0] mlu_res_21_n;
mac_tl Umtl_21_n             (.clk(clk), 
             .data_in(mlu_resx_21_n),
             .data_out(mlu_res_21_n));
defparam Umtl_21_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_22_n;
mlu_inf_2reg Umlu_22_n (.clk(clk), .data_in(tdl_dat_22_n), .coef_in(coef_st_22_n), .clk_en(clk_en), .mlu_out(mlu_resx_22_n) );
defparam Umlu_22_n.DATA_WIDTH = 16;
defparam Umlu_22_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_22_n.PIPE = 2;
defparam Umlu_22_n.DSP_USE = "YES";
wire [31:0] mlu_res_22_n;
mac_tl Umtl_22_n             (.clk(clk), 
             .data_in(mlu_resx_22_n),
             .data_out(mlu_res_22_n));
defparam Umtl_22_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_23_n;
mlu_inf_2reg Umlu_23_n (.clk(clk), .data_in(tdl_dat_23_n), .coef_in(coef_st_23_n), .clk_en(clk_en), .mlu_out(mlu_resx_23_n) );
defparam Umlu_23_n.DATA_WIDTH = 16;
defparam Umlu_23_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_23_n.PIPE = 2;
defparam Umlu_23_n.DSP_USE = "YES";
wire [31:0] mlu_res_23_n;
mac_tl Umtl_23_n             (.clk(clk), 
             .data_in(mlu_resx_23_n),
             .data_out(mlu_res_23_n));
defparam Umtl_23_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_24_n;
mlu_inf_2reg Umlu_24_n (.clk(clk), .data_in(tdl_dat_24_n), .coef_in(coef_st_24_n), .clk_en(clk_en), .mlu_out(mlu_resx_24_n) );
defparam Umlu_24_n.DATA_WIDTH = 16;
defparam Umlu_24_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_24_n.PIPE = 2;
defparam Umlu_24_n.DSP_USE = "YES";
wire [31:0] mlu_res_24_n;
mac_tl Umtl_24_n             (.clk(clk), 
             .data_in(mlu_resx_24_n),
             .data_out(mlu_res_24_n));
defparam Umtl_24_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_25_n;
mlu_inf_2reg Umlu_25_n (.clk(clk), .data_in(tdl_dat_25_n), .coef_in(coef_st_25_n), .clk_en(clk_en), .mlu_out(mlu_resx_25_n) );
defparam Umlu_25_n.DATA_WIDTH = 16;
defparam Umlu_25_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_25_n.PIPE = 2;
defparam Umlu_25_n.DSP_USE = "YES";
wire [31:0] mlu_res_25_n;
mac_tl Umtl_25_n             (.clk(clk), 
             .data_in(mlu_resx_25_n),
             .data_out(mlu_res_25_n));
defparam Umtl_25_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_26_n;
mlu_inf_2reg Umlu_26_n (.clk(clk), .data_in(tdl_dat_26_n), .coef_in(coef_st_26_n), .clk_en(clk_en), .mlu_out(mlu_resx_26_n) );
defparam Umlu_26_n.DATA_WIDTH = 16;
defparam Umlu_26_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_26_n.PIPE = 2;
defparam Umlu_26_n.DSP_USE = "YES";
wire [31:0] mlu_res_26_n;
mac_tl Umtl_26_n             (.clk(clk), 
             .data_in(mlu_resx_26_n),
             .data_out(mlu_res_26_n));
defparam Umtl_26_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_27_n;
mlu_inf_2reg Umlu_27_n (.clk(clk), .data_in(tdl_dat_27_n), .coef_in(coef_st_27_n), .clk_en(clk_en), .mlu_out(mlu_resx_27_n) );
defparam Umlu_27_n.DATA_WIDTH = 16;
defparam Umlu_27_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_27_n.PIPE = 2;
defparam Umlu_27_n.DSP_USE = "YES";
wire [31:0] mlu_res_27_n;
mac_tl Umtl_27_n             (.clk(clk), 
             .data_in(mlu_resx_27_n),
             .data_out(mlu_res_27_n));
defparam Umtl_27_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_28_n;
mlu_inf_2reg Umlu_28_n (.clk(clk), .data_in(tdl_dat_28_n), .coef_in(coef_st_28_n), .clk_en(clk_en), .mlu_out(mlu_resx_28_n) );
defparam Umlu_28_n.DATA_WIDTH = 16;
defparam Umlu_28_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_28_n.PIPE = 2;
defparam Umlu_28_n.DSP_USE = "YES";
wire [31:0] mlu_res_28_n;
mac_tl Umtl_28_n             (.clk(clk), 
             .data_in(mlu_resx_28_n),
             .data_out(mlu_res_28_n));
defparam Umtl_28_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_29_n;
mlu_inf_2reg Umlu_29_n (.clk(clk), .data_in(tdl_dat_29_n), .coef_in(coef_st_29_n), .clk_en(clk_en), .mlu_out(mlu_resx_29_n) );
defparam Umlu_29_n.DATA_WIDTH = 16;
defparam Umlu_29_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_29_n.PIPE = 2;
defparam Umlu_29_n.DSP_USE = "YES";
wire [31:0] mlu_res_29_n;
mac_tl Umtl_29_n             (.clk(clk), 
             .data_in(mlu_resx_29_n),
             .data_out(mlu_res_29_n));
defparam Umtl_29_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_30_n;
mlu_inf_2reg Umlu_30_n (.clk(clk), .data_in(tdl_dat_30_n), .coef_in(coef_st_30_n), .clk_en(clk_en), .mlu_out(mlu_resx_30_n) );
defparam Umlu_30_n.DATA_WIDTH = 16;
defparam Umlu_30_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_30_n.PIPE = 2;
defparam Umlu_30_n.DSP_USE = "YES";
wire [31:0] mlu_res_30_n;
mac_tl Umtl_30_n             (.clk(clk), 
             .data_in(mlu_resx_30_n),
             .data_out(mlu_res_30_n));
defparam Umtl_30_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_31_n;
mlu_inf_2reg Umlu_31_n (.clk(clk), .data_in(tdl_dat_31_n), .coef_in(coef_st_31_n), .clk_en(clk_en), .mlu_out(mlu_resx_31_n) );
defparam Umlu_31_n.DATA_WIDTH = 16;
defparam Umlu_31_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_31_n.PIPE = 2;
defparam Umlu_31_n.DSP_USE = "YES";
wire [31:0] mlu_res_31_n;
mac_tl Umtl_31_n             (.clk(clk), 
             .data_in(mlu_resx_31_n),
             .data_out(mlu_res_31_n));
defparam Umtl_31_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_32_n;
mlu_inf_2reg Umlu_32_n (.clk(clk), .data_in(tdl_dat_32_n), .coef_in(coef_st_32_n), .clk_en(clk_en), .mlu_out(mlu_resx_32_n) );
defparam Umlu_32_n.DATA_WIDTH = 16;
defparam Umlu_32_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_32_n.PIPE = 2;
defparam Umlu_32_n.DSP_USE = "YES";
wire [31:0] mlu_res_32_n;
mac_tl Umtl_32_n             (.clk(clk), 
             .data_in(mlu_resx_32_n),
             .data_out(mlu_res_32_n));
defparam Umtl_32_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_33_n;
mlu_inf_2reg Umlu_33_n (.clk(clk), .data_in(tdl_dat_33_n), .coef_in(coef_st_33_n), .clk_en(clk_en), .mlu_out(mlu_resx_33_n) );
defparam Umlu_33_n.DATA_WIDTH = 16;
defparam Umlu_33_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_33_n.PIPE = 2;
defparam Umlu_33_n.DSP_USE = "YES";
wire [31:0] mlu_res_33_n;
mac_tl Umtl_33_n             (.clk(clk), 
             .data_in(mlu_resx_33_n),
             .data_out(mlu_res_33_n));
defparam Umtl_33_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_34_n;
mlu_inf_2reg Umlu_34_n (.clk(clk), .data_in(tdl_dat_34_n), .coef_in(coef_st_34_n), .clk_en(clk_en), .mlu_out(mlu_resx_34_n) );
defparam Umlu_34_n.DATA_WIDTH = 16;
defparam Umlu_34_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_34_n.PIPE = 2;
defparam Umlu_34_n.DSP_USE = "YES";
wire [31:0] mlu_res_34_n;
mac_tl Umtl_34_n             (.clk(clk), 
             .data_in(mlu_resx_34_n),
             .data_out(mlu_res_34_n));
defparam Umtl_34_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_35_n;
mlu_inf_2reg Umlu_35_n (.clk(clk), .data_in(tdl_dat_35_n), .coef_in(coef_st_35_n), .clk_en(clk_en), .mlu_out(mlu_resx_35_n) );
defparam Umlu_35_n.DATA_WIDTH = 16;
defparam Umlu_35_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_35_n.PIPE = 2;
defparam Umlu_35_n.DSP_USE = "YES";
wire [31:0] mlu_res_35_n;
mac_tl Umtl_35_n             (.clk(clk), 
             .data_in(mlu_resx_35_n),
             .data_out(mlu_res_35_n));
defparam Umtl_35_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_36_n;
mlu_inf_2reg Umlu_36_n (.clk(clk), .data_in(tdl_dat_36_n), .coef_in(coef_st_36_n), .clk_en(clk_en), .mlu_out(mlu_resx_36_n) );
defparam Umlu_36_n.DATA_WIDTH = 16;
defparam Umlu_36_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_36_n.PIPE = 2;
defparam Umlu_36_n.DSP_USE = "YES";
wire [31:0] mlu_res_36_n;
mac_tl Umtl_36_n             (.clk(clk), 
             .data_in(mlu_resx_36_n),
             .data_out(mlu_res_36_n));
defparam Umtl_36_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_37_n;
mlu_inf_2reg Umlu_37_n (.clk(clk), .data_in(tdl_dat_37_n), .coef_in(coef_st_37_n), .clk_en(clk_en), .mlu_out(mlu_resx_37_n) );
defparam Umlu_37_n.DATA_WIDTH = 16;
defparam Umlu_37_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_37_n.PIPE = 2;
defparam Umlu_37_n.DSP_USE = "YES";
wire [31:0] mlu_res_37_n;
mac_tl Umtl_37_n             (.clk(clk), 
             .data_in(mlu_resx_37_n),
             .data_out(mlu_res_37_n));
defparam Umtl_37_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_38_n;
mlu_inf_2reg Umlu_38_n (.clk(clk), .data_in(tdl_dat_38_n), .coef_in(coef_st_38_n), .clk_en(clk_en), .mlu_out(mlu_resx_38_n) );
defparam Umlu_38_n.DATA_WIDTH = 16;
defparam Umlu_38_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_38_n.PIPE = 2;
defparam Umlu_38_n.DSP_USE = "YES";
wire [31:0] mlu_res_38_n;
mac_tl Umtl_38_n             (.clk(clk), 
             .data_in(mlu_resx_38_n),
             .data_out(mlu_res_38_n));
defparam Umtl_38_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_39_n;
mlu_inf_2reg Umlu_39_n (.clk(clk), .data_in(tdl_dat_39_n), .coef_in(coef_st_39_n), .clk_en(clk_en), .mlu_out(mlu_resx_39_n) );
defparam Umlu_39_n.DATA_WIDTH = 16;
defparam Umlu_39_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_39_n.PIPE = 2;
defparam Umlu_39_n.DSP_USE = "YES";
wire [31:0] mlu_res_39_n;
mac_tl Umtl_39_n             (.clk(clk), 
             .data_in(mlu_resx_39_n),
             .data_out(mlu_res_39_n));
defparam Umtl_39_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_40_n;
mlu_inf_2reg Umlu_40_n (.clk(clk), .data_in(tdl_dat_40_n), .coef_in(coef_st_40_n), .clk_en(clk_en), .mlu_out(mlu_resx_40_n) );
defparam Umlu_40_n.DATA_WIDTH = 16;
defparam Umlu_40_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_40_n.PIPE = 2;
defparam Umlu_40_n.DSP_USE = "YES";
wire [31:0] mlu_res_40_n;
mac_tl Umtl_40_n             (.clk(clk), 
             .data_in(mlu_resx_40_n),
             .data_out(mlu_res_40_n));
defparam Umtl_40_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_41_n;
mlu_inf_2reg Umlu_41_n (.clk(clk), .data_in(tdl_dat_41_n), .coef_in(coef_st_41_n), .clk_en(clk_en), .mlu_out(mlu_resx_41_n) );
defparam Umlu_41_n.DATA_WIDTH = 16;
defparam Umlu_41_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_41_n.PIPE = 2;
defparam Umlu_41_n.DSP_USE = "YES";
wire [31:0] mlu_res_41_n;
mac_tl Umtl_41_n             (.clk(clk), 
             .data_in(mlu_resx_41_n),
             .data_out(mlu_res_41_n));
defparam Umtl_41_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_42_n;
mlu_inf_2reg Umlu_42_n (.clk(clk), .data_in(tdl_dat_42_n), .coef_in(coef_st_42_n), .clk_en(clk_en), .mlu_out(mlu_resx_42_n) );
defparam Umlu_42_n.DATA_WIDTH = 16;
defparam Umlu_42_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_42_n.PIPE = 2;
defparam Umlu_42_n.DSP_USE = "YES";
wire [31:0] mlu_res_42_n;
mac_tl Umtl_42_n             (.clk(clk), 
             .data_in(mlu_resx_42_n),
             .data_out(mlu_res_42_n));
defparam Umtl_42_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_43_n;
mlu_inf_2reg Umlu_43_n (.clk(clk), .data_in(tdl_dat_43_n), .coef_in(coef_st_43_n), .clk_en(clk_en), .mlu_out(mlu_resx_43_n) );
defparam Umlu_43_n.DATA_WIDTH = 16;
defparam Umlu_43_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_43_n.PIPE = 2;
defparam Umlu_43_n.DSP_USE = "YES";
wire [31:0] mlu_res_43_n;
mac_tl Umtl_43_n             (.clk(clk), 
             .data_in(mlu_resx_43_n),
             .data_out(mlu_res_43_n));
defparam Umtl_43_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_44_n;
mlu_inf_2reg Umlu_44_n (.clk(clk), .data_in(tdl_dat_44_n), .coef_in(coef_st_44_n), .clk_en(clk_en), .mlu_out(mlu_resx_44_n) );
defparam Umlu_44_n.DATA_WIDTH = 16;
defparam Umlu_44_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_44_n.PIPE = 2;
defparam Umlu_44_n.DSP_USE = "YES";
wire [31:0] mlu_res_44_n;
mac_tl Umtl_44_n             (.clk(clk), 
             .data_in(mlu_resx_44_n),
             .data_out(mlu_res_44_n));
defparam Umtl_44_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_45_n;
mlu_inf_2reg Umlu_45_n (.clk(clk), .data_in(tdl_dat_45_n), .coef_in(coef_st_45_n), .clk_en(clk_en), .mlu_out(mlu_resx_45_n) );
defparam Umlu_45_n.DATA_WIDTH = 16;
defparam Umlu_45_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_45_n.PIPE = 2;
defparam Umlu_45_n.DSP_USE = "YES";
wire [31:0] mlu_res_45_n;
mac_tl Umtl_45_n             (.clk(clk), 
             .data_in(mlu_resx_45_n),
             .data_out(mlu_res_45_n));
defparam Umtl_45_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_46_n;
mlu_inf_2reg Umlu_46_n (.clk(clk), .data_in(tdl_dat_46_n), .coef_in(coef_st_46_n), .clk_en(clk_en), .mlu_out(mlu_resx_46_n) );
defparam Umlu_46_n.DATA_WIDTH = 16;
defparam Umlu_46_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_46_n.PIPE = 2;
defparam Umlu_46_n.DSP_USE = "YES";
wire [31:0] mlu_res_46_n;
mac_tl Umtl_46_n             (.clk(clk), 
             .data_in(mlu_resx_46_n),
             .data_out(mlu_res_46_n));
defparam Umtl_46_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_47_n;
mlu_inf_2reg Umlu_47_n (.clk(clk), .data_in(tdl_dat_47_n), .coef_in(coef_st_47_n), .clk_en(clk_en), .mlu_out(mlu_resx_47_n) );
defparam Umlu_47_n.DATA_WIDTH = 16;
defparam Umlu_47_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_47_n.PIPE = 2;
defparam Umlu_47_n.DSP_USE = "YES";
wire [31:0] mlu_res_47_n;
mac_tl Umtl_47_n             (.clk(clk), 
             .data_in(mlu_resx_47_n),
             .data_out(mlu_res_47_n));
defparam Umtl_47_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_48_n;
mlu_inf_2reg Umlu_48_n (.clk(clk), .data_in(tdl_dat_48_n), .coef_in(coef_st_48_n), .clk_en(clk_en), .mlu_out(mlu_resx_48_n) );
defparam Umlu_48_n.DATA_WIDTH = 16;
defparam Umlu_48_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_48_n.PIPE = 2;
defparam Umlu_48_n.DSP_USE = "YES";
wire [31:0] mlu_res_48_n;
mac_tl Umtl_48_n             (.clk(clk), 
             .data_in(mlu_resx_48_n),
             .data_out(mlu_res_48_n));
defparam Umtl_48_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_49_n;
mlu_inf_2reg Umlu_49_n (.clk(clk), .data_in(tdl_dat_49_n), .coef_in(coef_st_49_n), .clk_en(clk_en), .mlu_out(mlu_resx_49_n) );
defparam Umlu_49_n.DATA_WIDTH = 16;
defparam Umlu_49_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_49_n.PIPE = 2;
defparam Umlu_49_n.DSP_USE = "YES";
wire [31:0] mlu_res_49_n;
mac_tl Umtl_49_n             (.clk(clk), 
             .data_in(mlu_resx_49_n),
             .data_out(mlu_res_49_n));
defparam Umtl_49_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_50_n;
mlu_inf_2reg Umlu_50_n (.clk(clk), .data_in(tdl_dat_50_n), .coef_in(coef_st_50_n), .clk_en(clk_en), .mlu_out(mlu_resx_50_n) );
defparam Umlu_50_n.DATA_WIDTH = 16;
defparam Umlu_50_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_50_n.PIPE = 2;
defparam Umlu_50_n.DSP_USE = "YES";
wire [31:0] mlu_res_50_n;
mac_tl Umtl_50_n             (.clk(clk), 
             .data_in(mlu_resx_50_n),
             .data_out(mlu_res_50_n));
defparam Umtl_50_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_51_n;
mlu_inf_2reg Umlu_51_n (.clk(clk), .data_in(tdl_dat_51_n), .coef_in(coef_st_51_n), .clk_en(clk_en), .mlu_out(mlu_resx_51_n) );
defparam Umlu_51_n.DATA_WIDTH = 16;
defparam Umlu_51_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_51_n.PIPE = 2;
defparam Umlu_51_n.DSP_USE = "YES";
wire [31:0] mlu_res_51_n;
mac_tl Umtl_51_n             (.clk(clk), 
             .data_in(mlu_resx_51_n),
             .data_out(mlu_res_51_n));
defparam Umtl_51_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_52_n;
mlu_inf_2reg Umlu_52_n (.clk(clk), .data_in(tdl_dat_52_n), .coef_in(coef_st_52_n), .clk_en(clk_en), .mlu_out(mlu_resx_52_n) );
defparam Umlu_52_n.DATA_WIDTH = 16;
defparam Umlu_52_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_52_n.PIPE = 2;
defparam Umlu_52_n.DSP_USE = "YES";
wire [31:0] mlu_res_52_n;
mac_tl Umtl_52_n             (.clk(clk), 
             .data_in(mlu_resx_52_n),
             .data_out(mlu_res_52_n));
defparam Umtl_52_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_53_n;
mlu_inf_2reg Umlu_53_n (.clk(clk), .data_in(tdl_dat_53_n), .coef_in(coef_st_53_n), .clk_en(clk_en), .mlu_out(mlu_resx_53_n) );
defparam Umlu_53_n.DATA_WIDTH = 16;
defparam Umlu_53_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_53_n.PIPE = 2;
defparam Umlu_53_n.DSP_USE = "YES";
wire [31:0] mlu_res_53_n;
mac_tl Umtl_53_n             (.clk(clk), 
             .data_in(mlu_resx_53_n),
             .data_out(mlu_res_53_n));
defparam Umtl_53_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_54_n;
mlu_inf_2reg Umlu_54_n (.clk(clk), .data_in(tdl_dat_54_n), .coef_in(coef_st_54_n), .clk_en(clk_en), .mlu_out(mlu_resx_54_n) );
defparam Umlu_54_n.DATA_WIDTH = 16;
defparam Umlu_54_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_54_n.PIPE = 2;
defparam Umlu_54_n.DSP_USE = "YES";
wire [31:0] mlu_res_54_n;
mac_tl Umtl_54_n             (.clk(clk), 
             .data_in(mlu_resx_54_n),
             .data_out(mlu_res_54_n));
defparam Umtl_54_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_55_n;
mlu_inf_2reg Umlu_55_n (.clk(clk), .data_in(tdl_dat_55_n), .coef_in(coef_st_55_n), .clk_en(clk_en), .mlu_out(mlu_resx_55_n) );
defparam Umlu_55_n.DATA_WIDTH = 16;
defparam Umlu_55_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_55_n.PIPE = 2;
defparam Umlu_55_n.DSP_USE = "YES";
wire [31:0] mlu_res_55_n;
mac_tl Umtl_55_n             (.clk(clk), 
             .data_in(mlu_resx_55_n),
             .data_out(mlu_res_55_n));
defparam Umtl_55_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_56_n;
mlu_inf_2reg Umlu_56_n (.clk(clk), .data_in(tdl_dat_56_n), .coef_in(coef_st_56_n), .clk_en(clk_en), .mlu_out(mlu_resx_56_n) );
defparam Umlu_56_n.DATA_WIDTH = 16;
defparam Umlu_56_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_56_n.PIPE = 2;
defparam Umlu_56_n.DSP_USE = "YES";
wire [31:0] mlu_res_56_n;
mac_tl Umtl_56_n             (.clk(clk), 
             .data_in(mlu_resx_56_n),
             .data_out(mlu_res_56_n));
defparam Umtl_56_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_57_n;
mlu_inf_2reg Umlu_57_n (.clk(clk), .data_in(tdl_dat_57_n), .coef_in(coef_st_57_n), .clk_en(clk_en), .mlu_out(mlu_resx_57_n) );
defparam Umlu_57_n.DATA_WIDTH = 16;
defparam Umlu_57_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_57_n.PIPE = 2;
defparam Umlu_57_n.DSP_USE = "YES";
wire [31:0] mlu_res_57_n;
mac_tl Umtl_57_n             (.clk(clk), 
             .data_in(mlu_resx_57_n),
             .data_out(mlu_res_57_n));
defparam Umtl_57_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_58_n;
mlu_inf_2reg Umlu_58_n (.clk(clk), .data_in(tdl_dat_58_n), .coef_in(coef_st_58_n), .clk_en(clk_en), .mlu_out(mlu_resx_58_n) );
defparam Umlu_58_n.DATA_WIDTH = 16;
defparam Umlu_58_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_58_n.PIPE = 2;
defparam Umlu_58_n.DSP_USE = "YES";
wire [31:0] mlu_res_58_n;
mac_tl Umtl_58_n             (.clk(clk), 
             .data_in(mlu_resx_58_n),
             .data_out(mlu_res_58_n));
defparam Umtl_58_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_59_n;
mlu_inf_2reg Umlu_59_n (.clk(clk), .data_in(tdl_dat_59_n), .coef_in(coef_st_59_n), .clk_en(clk_en), .mlu_out(mlu_resx_59_n) );
defparam Umlu_59_n.DATA_WIDTH = 16;
defparam Umlu_59_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_59_n.PIPE = 2;
defparam Umlu_59_n.DSP_USE = "YES";
wire [31:0] mlu_res_59_n;
mac_tl Umtl_59_n             (.clk(clk), 
             .data_in(mlu_resx_59_n),
             .data_out(mlu_res_59_n));
defparam Umtl_59_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_60_n;
mlu_inf_2reg Umlu_60_n (.clk(clk), .data_in(tdl_dat_60_n), .coef_in(coef_st_60_n), .clk_en(clk_en), .mlu_out(mlu_resx_60_n) );
defparam Umlu_60_n.DATA_WIDTH = 16;
defparam Umlu_60_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_60_n.PIPE = 2;
defparam Umlu_60_n.DSP_USE = "YES";
wire [31:0] mlu_res_60_n;
mac_tl Umtl_60_n             (.clk(clk), 
             .data_in(mlu_resx_60_n),
             .data_out(mlu_res_60_n));
defparam Umtl_60_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_61_n;
mlu_inf_2reg Umlu_61_n (.clk(clk), .data_in(tdl_dat_61_n), .coef_in(coef_st_61_n), .clk_en(clk_en), .mlu_out(mlu_resx_61_n) );
defparam Umlu_61_n.DATA_WIDTH = 16;
defparam Umlu_61_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_61_n.PIPE = 2;
defparam Umlu_61_n.DSP_USE = "YES";
wire [31:0] mlu_res_61_n;
mac_tl Umtl_61_n             (.clk(clk), 
             .data_in(mlu_resx_61_n),
             .data_out(mlu_res_61_n));
defparam Umtl_61_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_62_n;
mlu_inf_2reg Umlu_62_n (.clk(clk), .data_in(tdl_dat_62_n), .coef_in(coef_st_62_n), .clk_en(clk_en), .mlu_out(mlu_resx_62_n) );
defparam Umlu_62_n.DATA_WIDTH = 16;
defparam Umlu_62_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_62_n.PIPE = 2;
defparam Umlu_62_n.DSP_USE = "YES";
wire [31:0] mlu_res_62_n;
mac_tl Umtl_62_n             (.clk(clk), 
             .data_in(mlu_resx_62_n),
             .data_out(mlu_res_62_n));
defparam Umtl_62_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_63_n;
mlu_inf_2reg Umlu_63_n (.clk(clk), .data_in(tdl_dat_63_n), .coef_in(coef_st_63_n), .clk_en(clk_en), .mlu_out(mlu_resx_63_n) );
defparam Umlu_63_n.DATA_WIDTH = 16;
defparam Umlu_63_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_63_n.PIPE = 2;
defparam Umlu_63_n.DSP_USE = "YES";
wire [31:0] mlu_res_63_n;
mac_tl Umtl_63_n             (.clk(clk), 
             .data_in(mlu_resx_63_n),
             .data_out(mlu_res_63_n));
defparam Umtl_63_n.DATA_WIDTH = 32;

wire [31:0] mlu_resx_64_n;
mlu_inf_2reg Umlu_64_n (.clk(clk), .data_in(tdl_dat_64_n), .coef_in(coef_st_64_n), .clk_en(clk_en), .mlu_out(mlu_resx_64_n) );
defparam Umlu_64_n.DATA_WIDTH = 16;
defparam Umlu_64_n.COEF_WIDTH = COEF_WIDTH;
defparam Umlu_64_n.PIPE = 2;
defparam Umlu_64_n.DSP_USE = "YES";
wire [31:0] mlu_res_64_n;
mac_tl Umtl_64_n             (.clk(clk), 
             .data_in(mlu_resx_64_n),
             .data_out(mlu_res_64_n));
defparam Umtl_64_n.DATA_WIDTH = 32;

wire [32:0] tree_l_0_n_0_n;
sadd_c_cen Uaddl_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_0_n), .bin(mlu_res_1_n), .res(tree_l_0_n_0_n) );
defparam Uaddl_0_n_0_n.IN_WIDTH = 32;
defparam Uaddl_0_n_0_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_1_n;
sadd_c_cen Uaddl_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_2_n), .bin(mlu_res_3_n), .res(tree_l_0_n_1_n) );
defparam Uaddl_0_n_1_n.IN_WIDTH = 32;
defparam Uaddl_0_n_1_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_2_n;
sadd_c_cen Uaddl_0_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_4_n), .bin(mlu_res_5_n), .res(tree_l_0_n_2_n) );
defparam Uaddl_0_n_2_n.IN_WIDTH = 32;
defparam Uaddl_0_n_2_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_3_n;
sadd_c_cen Uaddl_0_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_6_n), .bin(mlu_res_7_n), .res(tree_l_0_n_3_n) );
defparam Uaddl_0_n_3_n.IN_WIDTH = 32;
defparam Uaddl_0_n_3_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_4_n;
sadd_c_cen Uaddl_0_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_8_n), .bin(mlu_res_9_n), .res(tree_l_0_n_4_n) );
defparam Uaddl_0_n_4_n.IN_WIDTH = 32;
defparam Uaddl_0_n_4_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_5_n;
sadd_c_cen Uaddl_0_n_5_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_10_n), .bin(mlu_res_11_n), .res(tree_l_0_n_5_n) );
defparam Uaddl_0_n_5_n.IN_WIDTH = 32;
defparam Uaddl_0_n_5_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_6_n;
sadd_c_cen Uaddl_0_n_6_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_12_n), .bin(mlu_res_13_n), .res(tree_l_0_n_6_n) );
defparam Uaddl_0_n_6_n.IN_WIDTH = 32;
defparam Uaddl_0_n_6_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_7_n;
sadd_c_cen Uaddl_0_n_7_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_14_n), .bin(mlu_res_15_n), .res(tree_l_0_n_7_n) );
defparam Uaddl_0_n_7_n.IN_WIDTH = 32;
defparam Uaddl_0_n_7_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_8_n;
sadd_c_cen Uaddl_0_n_8_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_16_n), .bin(mlu_res_17_n), .res(tree_l_0_n_8_n) );
defparam Uaddl_0_n_8_n.IN_WIDTH = 32;
defparam Uaddl_0_n_8_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_9_n;
sadd_c_cen Uaddl_0_n_9_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_18_n), .bin(mlu_res_19_n), .res(tree_l_0_n_9_n) );
defparam Uaddl_0_n_9_n.IN_WIDTH = 32;
defparam Uaddl_0_n_9_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_10_n;
sadd_c_cen Uaddl_0_n_10_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_20_n), .bin(mlu_res_21_n), .res(tree_l_0_n_10_n) );
defparam Uaddl_0_n_10_n.IN_WIDTH = 32;
defparam Uaddl_0_n_10_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_11_n;
sadd_c_cen Uaddl_0_n_11_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_22_n), .bin(mlu_res_23_n), .res(tree_l_0_n_11_n) );
defparam Uaddl_0_n_11_n.IN_WIDTH = 32;
defparam Uaddl_0_n_11_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_12_n;
sadd_c_cen Uaddl_0_n_12_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_24_n), .bin(mlu_res_25_n), .res(tree_l_0_n_12_n) );
defparam Uaddl_0_n_12_n.IN_WIDTH = 32;
defparam Uaddl_0_n_12_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_13_n;
sadd_c_cen Uaddl_0_n_13_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_26_n), .bin(mlu_res_27_n), .res(tree_l_0_n_13_n) );
defparam Uaddl_0_n_13_n.IN_WIDTH = 32;
defparam Uaddl_0_n_13_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_14_n;
sadd_c_cen Uaddl_0_n_14_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_28_n), .bin(mlu_res_29_n), .res(tree_l_0_n_14_n) );
defparam Uaddl_0_n_14_n.IN_WIDTH = 32;
defparam Uaddl_0_n_14_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_15_n;
sadd_c_cen Uaddl_0_n_15_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_30_n), .bin(mlu_res_31_n), .res(tree_l_0_n_15_n) );
defparam Uaddl_0_n_15_n.IN_WIDTH = 32;
defparam Uaddl_0_n_15_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_16_n;
sadd_c_cen Uaddl_0_n_16_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_32_n), .bin(mlu_res_33_n), .res(tree_l_0_n_16_n) );
defparam Uaddl_0_n_16_n.IN_WIDTH = 32;
defparam Uaddl_0_n_16_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_17_n;
sadd_c_cen Uaddl_0_n_17_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_34_n), .bin(mlu_res_35_n), .res(tree_l_0_n_17_n) );
defparam Uaddl_0_n_17_n.IN_WIDTH = 32;
defparam Uaddl_0_n_17_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_18_n;
sadd_c_cen Uaddl_0_n_18_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_36_n), .bin(mlu_res_37_n), .res(tree_l_0_n_18_n) );
defparam Uaddl_0_n_18_n.IN_WIDTH = 32;
defparam Uaddl_0_n_18_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_19_n;
sadd_c_cen Uaddl_0_n_19_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_38_n), .bin(mlu_res_39_n), .res(tree_l_0_n_19_n) );
defparam Uaddl_0_n_19_n.IN_WIDTH = 32;
defparam Uaddl_0_n_19_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_20_n;
sadd_c_cen Uaddl_0_n_20_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_40_n), .bin(mlu_res_41_n), .res(tree_l_0_n_20_n) );
defparam Uaddl_0_n_20_n.IN_WIDTH = 32;
defparam Uaddl_0_n_20_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_21_n;
sadd_c_cen Uaddl_0_n_21_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_42_n), .bin(mlu_res_43_n), .res(tree_l_0_n_21_n) );
defparam Uaddl_0_n_21_n.IN_WIDTH = 32;
defparam Uaddl_0_n_21_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_22_n;
sadd_c_cen Uaddl_0_n_22_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_44_n), .bin(mlu_res_45_n), .res(tree_l_0_n_22_n) );
defparam Uaddl_0_n_22_n.IN_WIDTH = 32;
defparam Uaddl_0_n_22_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_23_n;
sadd_c_cen Uaddl_0_n_23_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_46_n), .bin(mlu_res_47_n), .res(tree_l_0_n_23_n) );
defparam Uaddl_0_n_23_n.IN_WIDTH = 32;
defparam Uaddl_0_n_23_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_24_n;
sadd_c_cen Uaddl_0_n_24_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_48_n), .bin(mlu_res_49_n), .res(tree_l_0_n_24_n) );
defparam Uaddl_0_n_24_n.IN_WIDTH = 32;
defparam Uaddl_0_n_24_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_25_n;
sadd_c_cen Uaddl_0_n_25_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_50_n), .bin(mlu_res_51_n), .res(tree_l_0_n_25_n) );
defparam Uaddl_0_n_25_n.IN_WIDTH = 32;
defparam Uaddl_0_n_25_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_26_n;
sadd_c_cen Uaddl_0_n_26_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_52_n), .bin(mlu_res_53_n), .res(tree_l_0_n_26_n) );
defparam Uaddl_0_n_26_n.IN_WIDTH = 32;
defparam Uaddl_0_n_26_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_27_n;
sadd_c_cen Uaddl_0_n_27_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_54_n), .bin(mlu_res_55_n), .res(tree_l_0_n_27_n) );
defparam Uaddl_0_n_27_n.IN_WIDTH = 32;
defparam Uaddl_0_n_27_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_28_n;
sadd_c_cen Uaddl_0_n_28_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_56_n), .bin(mlu_res_57_n), .res(tree_l_0_n_28_n) );
defparam Uaddl_0_n_28_n.IN_WIDTH = 32;
defparam Uaddl_0_n_28_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_29_n;
sadd_c_cen Uaddl_0_n_29_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_58_n), .bin(mlu_res_59_n), .res(tree_l_0_n_29_n) );
defparam Uaddl_0_n_29_n.IN_WIDTH = 32;
defparam Uaddl_0_n_29_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_30_n;
sadd_c_cen Uaddl_0_n_30_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_60_n), .bin(mlu_res_61_n), .res(tree_l_0_n_30_n) );
defparam Uaddl_0_n_30_n.IN_WIDTH = 32;
defparam Uaddl_0_n_30_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_31_n;
sadd_c_cen Uaddl_0_n_31_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_62_n), .bin(mlu_res_63_n), .res(tree_l_0_n_31_n) );
defparam Uaddl_0_n_31_n.IN_WIDTH = 32;
defparam Uaddl_0_n_31_n.PIPE_DEPTH = 1;
wire [32:0] tree_l_0_n_32_n;
sadd_c_cen Uaddl_0_n_32_n (.clk(clk),  .gclk_en(clk_en), .ain(mlu_res_64_n), .bin(32'd0), .res(tree_l_0_n_32_n) );
defparam Uaddl_0_n_32_n.IN_WIDTH = 32;
defparam Uaddl_0_n_32_n.PIPE_DEPTH = 1;

wire [33:0] tree_l_1_n_0_n;
sadd_cen Uaddl_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_0_n), .bin(tree_l_0_n_1_n), .res(tree_l_1_n_0_n) );
defparam Uaddl_1_n_0_n.IN_WIDTH = 33;
defparam Uaddl_1_n_0_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_1_n;
sadd_cen Uaddl_1_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_2_n), .bin(tree_l_0_n_3_n), .res(tree_l_1_n_1_n) );
defparam Uaddl_1_n_1_n.IN_WIDTH = 33;
defparam Uaddl_1_n_1_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_2_n;
sadd_cen Uaddl_1_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_4_n), .bin(tree_l_0_n_5_n), .res(tree_l_1_n_2_n) );
defparam Uaddl_1_n_2_n.IN_WIDTH = 33;
defparam Uaddl_1_n_2_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_3_n;
sadd_cen Uaddl_1_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_6_n), .bin(tree_l_0_n_7_n), .res(tree_l_1_n_3_n) );
defparam Uaddl_1_n_3_n.IN_WIDTH = 33;
defparam Uaddl_1_n_3_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_4_n;
sadd_cen Uaddl_1_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_8_n), .bin(tree_l_0_n_9_n), .res(tree_l_1_n_4_n) );
defparam Uaddl_1_n_4_n.IN_WIDTH = 33;
defparam Uaddl_1_n_4_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_5_n;
sadd_cen Uaddl_1_n_5_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_10_n), .bin(tree_l_0_n_11_n), .res(tree_l_1_n_5_n) );
defparam Uaddl_1_n_5_n.IN_WIDTH = 33;
defparam Uaddl_1_n_5_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_6_n;
sadd_cen Uaddl_1_n_6_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_12_n), .bin(tree_l_0_n_13_n), .res(tree_l_1_n_6_n) );
defparam Uaddl_1_n_6_n.IN_WIDTH = 33;
defparam Uaddl_1_n_6_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_7_n;
sadd_cen Uaddl_1_n_7_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_14_n), .bin(tree_l_0_n_15_n), .res(tree_l_1_n_7_n) );
defparam Uaddl_1_n_7_n.IN_WIDTH = 33;
defparam Uaddl_1_n_7_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_8_n;
sadd_cen Uaddl_1_n_8_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_16_n), .bin(tree_l_0_n_17_n), .res(tree_l_1_n_8_n) );
defparam Uaddl_1_n_8_n.IN_WIDTH = 33;
defparam Uaddl_1_n_8_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_9_n;
sadd_cen Uaddl_1_n_9_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_18_n), .bin(tree_l_0_n_19_n), .res(tree_l_1_n_9_n) );
defparam Uaddl_1_n_9_n.IN_WIDTH = 33;
defparam Uaddl_1_n_9_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_10_n;
sadd_cen Uaddl_1_n_10_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_20_n), .bin(tree_l_0_n_21_n), .res(tree_l_1_n_10_n) );
defparam Uaddl_1_n_10_n.IN_WIDTH = 33;
defparam Uaddl_1_n_10_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_11_n;
sadd_cen Uaddl_1_n_11_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_22_n), .bin(tree_l_0_n_23_n), .res(tree_l_1_n_11_n) );
defparam Uaddl_1_n_11_n.IN_WIDTH = 33;
defparam Uaddl_1_n_11_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_12_n;
sadd_cen Uaddl_1_n_12_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_24_n), .bin(tree_l_0_n_25_n), .res(tree_l_1_n_12_n) );
defparam Uaddl_1_n_12_n.IN_WIDTH = 33;
defparam Uaddl_1_n_12_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_13_n;
sadd_cen Uaddl_1_n_13_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_26_n), .bin(tree_l_0_n_27_n), .res(tree_l_1_n_13_n) );
defparam Uaddl_1_n_13_n.IN_WIDTH = 33;
defparam Uaddl_1_n_13_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_14_n;
sadd_cen Uaddl_1_n_14_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_28_n), .bin(tree_l_0_n_29_n), .res(tree_l_1_n_14_n) );
defparam Uaddl_1_n_14_n.IN_WIDTH = 33;
defparam Uaddl_1_n_14_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_15_n;
sadd_cen Uaddl_1_n_15_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_30_n), .bin(tree_l_0_n_31_n), .res(tree_l_1_n_15_n) );
defparam Uaddl_1_n_15_n.IN_WIDTH = 33;
defparam Uaddl_1_n_15_n.PIPE_DEPTH = 1;
wire [33:0] tree_l_1_n_16_n;
sadd_cen Uaddl_1_n_16_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_0_n_32_n), .bin(33'd0), .res(tree_l_1_n_16_n) );
defparam Uaddl_1_n_16_n.IN_WIDTH = 33;
defparam Uaddl_1_n_16_n.PIPE_DEPTH = 1;

wire [34:0] tree_l_2_n_0_n;
sadd_reg_top_cen Uaddl_2_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_0_n), .bin(tree_l_1_n_1_n), .res(tree_l_2_n_0_n) );
defparam Uaddl_2_n_0_n.IN_WIDTH = 34;
defparam Uaddl_2_n_0_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_1_n;
sadd_reg_top_cen Uaddl_2_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_2_n), .bin(tree_l_1_n_3_n), .res(tree_l_2_n_1_n) );
defparam Uaddl_2_n_1_n.IN_WIDTH = 34;
defparam Uaddl_2_n_1_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_2_n;
sadd_reg_top_cen Uaddl_2_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_4_n), .bin(tree_l_1_n_5_n), .res(tree_l_2_n_2_n) );
defparam Uaddl_2_n_2_n.IN_WIDTH = 34;
defparam Uaddl_2_n_2_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_3_n;
sadd_reg_top_cen Uaddl_2_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_6_n), .bin(tree_l_1_n_7_n), .res(tree_l_2_n_3_n) );
defparam Uaddl_2_n_3_n.IN_WIDTH = 34;
defparam Uaddl_2_n_3_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_4_n;
sadd_reg_top_cen Uaddl_2_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_8_n), .bin(tree_l_1_n_9_n), .res(tree_l_2_n_4_n) );
defparam Uaddl_2_n_4_n.IN_WIDTH = 34;
defparam Uaddl_2_n_4_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_5_n;
sadd_reg_top_cen Uaddl_2_n_5_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_10_n), .bin(tree_l_1_n_11_n), .res(tree_l_2_n_5_n) );
defparam Uaddl_2_n_5_n.IN_WIDTH = 34;
defparam Uaddl_2_n_5_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_6_n;
sadd_reg_top_cen Uaddl_2_n_6_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_12_n), .bin(tree_l_1_n_13_n), .res(tree_l_2_n_6_n) );
defparam Uaddl_2_n_6_n.IN_WIDTH = 34;
defparam Uaddl_2_n_6_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_7_n;
sadd_reg_top_cen Uaddl_2_n_7_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_14_n), .bin(tree_l_1_n_15_n), .res(tree_l_2_n_7_n) );
defparam Uaddl_2_n_7_n.IN_WIDTH = 34;
defparam Uaddl_2_n_7_n.PIPE_DEPTH = 1;
wire [34:0] tree_l_2_n_8_n;
sadd_reg_top_cen Uaddl_2_n_8_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_1_n_16_n), .bin(34'd0), .res(tree_l_2_n_8_n) );
defparam Uaddl_2_n_8_n.IN_WIDTH = 34;
defparam Uaddl_2_n_8_n.PIPE_DEPTH = 1;

wire [35:0] tree_l_3_n_0_n;
sadd_reg_top_cen Uaddl_3_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_0_n), .bin(tree_l_2_n_1_n), .res(tree_l_3_n_0_n) );
defparam Uaddl_3_n_0_n.IN_WIDTH = 35;
defparam Uaddl_3_n_0_n.PIPE_DEPTH = 1;
wire [35:0] tree_l_3_n_1_n;
sadd_reg_top_cen Uaddl_3_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_2_n), .bin(tree_l_2_n_3_n), .res(tree_l_3_n_1_n) );
defparam Uaddl_3_n_1_n.IN_WIDTH = 35;
defparam Uaddl_3_n_1_n.PIPE_DEPTH = 1;
wire [35:0] tree_l_3_n_2_n;
sadd_reg_top_cen Uaddl_3_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_4_n), .bin(tree_l_2_n_5_n), .res(tree_l_3_n_2_n) );
defparam Uaddl_3_n_2_n.IN_WIDTH = 35;
defparam Uaddl_3_n_2_n.PIPE_DEPTH = 1;
wire [35:0] tree_l_3_n_3_n;
sadd_reg_top_cen Uaddl_3_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_6_n), .bin(tree_l_2_n_7_n), .res(tree_l_3_n_3_n) );
defparam Uaddl_3_n_3_n.IN_WIDTH = 35;
defparam Uaddl_3_n_3_n.PIPE_DEPTH = 1;
wire [35:0] tree_l_3_n_4_n;
sadd_reg_top_cen Uaddl_3_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_2_n_8_n), .bin(35'd0), .res(tree_l_3_n_4_n) );
defparam Uaddl_3_n_4_n.IN_WIDTH = 35;
defparam Uaddl_3_n_4_n.PIPE_DEPTH = 1;

wire [36:0] tree_l_4_n_0_n;
sadd_reg_top_cen Uaddl_4_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_3_n_0_n), .bin(tree_l_3_n_1_n), .res(tree_l_4_n_0_n) );
defparam Uaddl_4_n_0_n.IN_WIDTH = 36;
defparam Uaddl_4_n_0_n.PIPE_DEPTH = 1;
wire [36:0] tree_l_4_n_1_n;
sadd_reg_top_cen Uaddl_4_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_3_n_2_n), .bin(tree_l_3_n_3_n), .res(tree_l_4_n_1_n) );
defparam Uaddl_4_n_1_n.IN_WIDTH = 36;
defparam Uaddl_4_n_1_n.PIPE_DEPTH = 1;
wire [36:0] tree_l_4_n_2_n;
sadd_reg_top_cen Uaddl_4_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_3_n_4_n), .bin(36'd0), .res(tree_l_4_n_2_n) );
defparam Uaddl_4_n_2_n.IN_WIDTH = 36;
defparam Uaddl_4_n_2_n.PIPE_DEPTH = 1;

wire [37:0] tree_l_5_n_0_n;
sadd_reg_top_cen Uaddl_5_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_4_n_0_n), .bin(tree_l_4_n_1_n), .res(tree_l_5_n_0_n) );
defparam Uaddl_5_n_0_n.IN_WIDTH = 37;
defparam Uaddl_5_n_0_n.PIPE_DEPTH = 1;
wire [37:0] tree_l_5_n_1_n;
sadd_reg_top_cen Uaddl_5_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_4_n_2_n), .bin(37'd0), .res(tree_l_5_n_1_n) );
defparam Uaddl_5_n_1_n.IN_WIDTH = 37;
defparam Uaddl_5_n_1_n.PIPE_DEPTH = 1;

wire [38:0] tree_l_6_n_0_n;
sadd_reg_top_cen Uaddl_6_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_l_5_n_0_n), .bin(tree_l_5_n_1_n), .res(tree_l_6_n_0_n) );
defparam Uaddl_6_n_0_n.IN_WIDTH = 38;
defparam Uaddl_6_n_0_n.PIPE_DEPTH = 1;

wire [38:0] fir_mc_res;
assign fir_mc_res=tree_l_6_n_0_n;
wire [35:0] fir_temp_res;
assign fir_temp_res = fir_mc_res[ACCUM_WIDTH-1:0];
wire [35:0] fir_int_res;
lc_store_cen Ures_reg (.clk(clk), .ce(done_int), .rst(rst), .gclk_en(clk_en),.data_in(fir_temp_res[ACCUM_WIDTH-1:0]), .q(fir_int_res) );
defparam Ures_reg.WIDTH = ACCUM_WIDTH;
assign fir_result = fir_int_res;
scv_ctrl ctrl(.rst(rst), .clk(clk), .clk_en(clk_en), .input_ch_id(input_ch_id), .output_ch_id(output_ch_id), .done_int(done_int), .rdy_int(rdy_int), .coef_ld(coef_ld), 
.done(done), .data_ld(data_ld), .rdy_to_ld(rdy_to_ld));
defparam ctrl.REG_LEN   = 1;
defparam ctrl.PIPE_DLY  = 12;
defparam ctrl.NO_SYM   = 1; 
defparam ctrl.NUM_CH = 2;  
defparam ctrl.CH_WIDTH = 1; 

endmodule
